import type { Language } from '@/app/design/content';

type Labels = { qr: string; title: string; guestHelp: string; register: string; signIn: string; language: string; loading: string; older: string; guest: string; empty: string; message: string; placeholder: string; sending: string; send: string; unavailable: string; loadError: string; sendError: string };
const keys = ['qr', 'title', 'guestHelp', 'register', 'signIn', 'language', 'loading', 'older', 'guest', 'empty', 'message', 'placeholder', 'sending', 'send', 'unavailable', 'loadError', 'sendError'] as const;
const rows: Record<Language, string[]> = {
  ru: ['Мой QR-код', 'Личная переписка', 'Вы общаетесь как гость. Чат доступен в этом браузере, пока сохранена гостевая сессия.', 'Зарегистрироваться для постоянного QR-кода', 'Войти / зарегистрироваться', 'Язык общения', 'Загрузка сообщений…', 'Показать более ранние сообщения', 'Гость', 'Начните разговор. Сообщения видны только вам и собеседнику.', 'Сообщение', 'Написать сообщение…', 'Отправляем…', 'Отправить', 'Переписка недоступна. Войдите в аккаунт одного из участников.', 'Не удалось загрузить сообщения. Проверьте соединение и повторите.', 'Сообщение не отправлено. Проверьте соединение и повторите.'],
  en: ['My QR code', 'Private conversation', 'You are chatting as a guest. This chat is available in this browser while your guest session is saved.', 'Register for a permanent QR code', 'Sign in / register', 'Chat language', 'Loading messages…', 'Show older messages', 'Guest', 'Start a conversation. Only you and the other participant can see the messages.', 'Message', 'Write a message…', 'Sending…', 'Send', 'Conversation unavailable. Sign in as a participant.', 'Could not load messages. Check your connection and retry.', 'Message not sent. Check your connection and retry.'],
  ko: ['내 QR 코드', '개인 대화', '게스트로 대화하고 있습니다. 게스트 세션이 유지되는 동안 이 브라우저에서 채팅을 이용할 수 있습니다.', '영구 QR 코드를 받으려면 가입하세요', '로그인 / 회원가입', '대화 언어', '메시지 불러오는 중…', '이전 메시지 보기', '게스트', '대화를 시작하세요. 메시지는 나와 상대방만 볼 수 있습니다.', '메시지', '메시지를 입력하세요…', '전송 중…', '보내기', '대화를 이용할 수 없습니다. 참여자 계정으로 로그인하세요.', '메시지를 불러오지 못했습니다. 연결을 확인하고 다시 시도하세요.', '메시지를 보내지 못했습니다. 연결을 확인하고 다시 시도하세요.'],
  zh: ['我的二维码', '私人聊天', '您正在以访客身份聊天。访客会话保留期间，可在此浏览器中使用聊天。', '注册以获取永久二维码', '登录 / 注册', '聊天语言', '正在加载消息…', '查看更早的消息', '访客', '开始聊天吧。只有您和对方可以看到消息。', '消息', '输入消息…', '正在发送…', '发送', '无法访问聊天。请使用参与者的账号登录。', '无法加载消息。请检查网络连接后重试。', '消息未发送。请检查网络连接后重试。'],
  tr: ['QR kodum', 'Özel sohbet', 'Misafir olarak sohbet ediyorsunuz. Misafir oturumunuz korunduğu sürece sohbet bu tarayıcıda kullanılabilir.', 'Kalıcı QR kodu için kaydolun', 'Giriş yap / kaydol', 'Sohbet dili', 'Mesajlar yükleniyor…', 'Önceki mesajları göster', 'Misafir', 'Sohbeti başlatın. Mesajları yalnızca siz ve karşı taraf görebilir.', 'Mesaj', 'Mesaj yazın…', 'Gönderiliyor…', 'Gönder', 'Sohbete erişilemiyor. Katılımcı hesabıyla giriş yapın.', 'Mesajlar yüklenemedi. Bağlantınızı kontrol edip tekrar deneyin.', 'Mesaj gönderilemedi. Bağlantınızı kontrol edip tekrar deneyin.'],
  vi: ['Mã QR của tôi', 'Trò chuyện riêng', 'Bạn đang trò chuyện với tư cách khách. Cuộc trò chuyện có sẵn trong trình duyệt này khi phiên khách được lưu.', 'Đăng ký để có mã QR cố định', 'Đăng nhập / đăng ký', 'Ngôn ngữ trò chuyện', 'Đang tải tin nhắn…', 'Xem tin nhắn cũ hơn', 'Khách', 'Bắt đầu trò chuyện. Chỉ bạn và người đối thoại có thể xem tin nhắn.', 'Tin nhắn', 'Nhập tin nhắn…', 'Đang gửi…', 'Gửi', 'Không thể truy cập cuộc trò chuyện. Hãy đăng nhập bằng tài khoản người tham gia.', 'Không tải được tin nhắn. Kiểm tra kết nối và thử lại.', 'Chưa gửi được tin nhắn. Kiểm tra kết nối và thử lại.'],
  km: ['កូដ QR របស់ខ្ញុំ', 'ការសន្ទនាឯកជន', 'អ្នកកំពុងជជែកជាភ្ញៀវ។ ការជជែកនេះអាចប្រើបានក្នុងកម្មវិធីរុករកនេះ ដរាបណាវគ្គភ្ញៀវត្រូវបានរក្សាទុក។', 'ចុះឈ្មោះដើម្បីទទួលបានកូដ QR អចិន្ត្រៃយ៍', 'ចូល / ចុះឈ្មោះ', 'ភាសាជជែក', 'កំពុងផ្ទុកសារ…', 'បង្ហាញសារចាស់ៗ', 'ភ្ញៀវ', 'ចាប់ផ្តើមការសន្ទនា។ មានតែអ្នក និងដៃគូសន្ទនាប៉ុណ្ណោះដែលអាចមើលឃើញសារ។', 'សារ', 'សរសេរសារ…', 'កំពុងផ្ញើ…', 'ផ្ញើ', 'មិនអាចចូលការសន្ទនាបានទេ។ សូមចូលដោយគណនីអ្នកចូលរួម។', 'មិនអាចផ្ទុកសារបានទេ។ សូមពិនិត្យការតភ្ជាប់ ហើយព្យាយាមម្តងទៀត។', 'សារមិនបានផ្ញើទេ។ សូមពិនិត្យការតភ្ជាប់ ហើយព្យាយាមម្តងទៀត។'],
  kk: ['Менің QR-кодым', 'Жеке хат алмасу', 'Сіз қонақ ретінде сөйлесіп отырсыз. Қонақ сессиясы сақталғанша чат осы браузерде қолжетімді.', 'Тұрақты QR-код алу үшін тіркеліңіз', 'Кіру / тіркелу', 'Сөйлесу тілі', 'Хабарламалар жүктелуде…', 'Бұрынғы хабарламаларды көрсету', 'Қонақ', 'Әңгімені бастаңыз. Хабарламаларды тек сіз және сұхбаттасыңыз көре алады.', 'Хабарлама', 'Хабарлама жазыңыз…', 'Жіберілуде…', 'Жіберу', 'Хат алмасу қолжетімсіз. Қатысушының аккаунтына кіріңіз.', 'Хабарламалар жүктелмеді. Байланысты тексеріп, қайталаңыз.', 'Хабарлама жіберілмеді. Байланысты тексеріп, қайталаңыз.'],
};
export const privateChatLabels = Object.fromEntries(Object.entries(rows).map(([language, values]) => [language, Object.fromEntries(keys.map((key, index) => [key, values[index]]))])) as Record<Language, Labels>;
