const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const ts=require('typescript');
const messageId='11111111-1111-4111-8111-111111111111';
function setup({endpoint='https://web.push.apple.com/test',expired=false}={}){
 let handler;const queries=[],sent=[];
 const rows={esx_push_config:{public_key:'public',private_key:'private',webhook_secret:'secret'},esx_private_messages:{id:messageId,chat_id:messageId,sender_id:'sender'},esx_conversations:{participant_a:'sender',participant_b:'recipient'},esx_push_subscriptions:[{endpoint,user_id:'recipient',p256dh:'key',auth:'auth',language:'ru'}]};
 const db={from(table){const q={table,filters:[],operation:'select'};queries.push(q);const builder={select(){return builder},eq(k,v){q.filters.push([k,v]);return builder},delete(){q.operation='delete';return builder},single(){return Promise.resolve({data:rows[table]})},maybeSingle(){return builder.single()},then(resolve){return Promise.resolve({data:rows[table]}).then(resolve)}};return builder}};
 const webpush={setVapidDetails(){},async sendNotification(sub,payload){sent.push({sub,payload:JSON.parse(payload)});if(expired)throw {statusCode:410}}};
 const source=ts.transpileModule(fs.readFileSync('supabase/functions/esx-push/index.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,esModuleInterop:true}}).outputText;
 vm.runInNewContext(source,{exports:{},require:p=>p.includes('supabase-js')?{createClient:()=>db}:webpush,Deno:{env:{get:()=>''},serve:fn=>handler=fn},Response,URL});
 return {queries,sent,call:async(method='POST',secret='secret')=>handler(new Request('https://test.invalid',{method,headers:{'x-esx-push-secret':secret},...(method==='POST'?{body:JSON.stringify({messageId})}:{})}))};
}
test('public configuration exposes only the public key',async()=>{const h=setup();assert.deepEqual(await (await h.call('GET')).json(),{publicKey:'public'});assert.equal(h.sent.length,0)});
test('unauthorized requests cannot send notifications or load messages',async()=>{const h=setup();assert.equal((await h.call('POST','wrong')).status,401);assert.equal(h.sent.length,0);assert.equal(h.queries.length,1)});
test('only recipient subscriptions are selected and message content is excluded',async()=>{const h=setup();assert.equal((await h.call()).status,200);assert.deepEqual(h.queries.find(q=>q.table==='esx_push_subscriptions').filters,[['user_id','recipient']]);assert.equal(h.sent.length,1);assert.equal(h.sent[0].payload.body,'Новое сообщение в ESX');assert.equal(h.sent[0].payload.url,'/messages/'+messageId);assert.equal(h.sent[0].payload.message,undefined)});
test('arbitrary network destinations are rejected',async()=>{for(const endpoint of ['http://localhost/test','https://127.0.0.1/test','https://web.push.apple.com.evil.test/test','https://web.push.apple.com:8443/test']){const h=setup({endpoint});assert.equal((await h.call()).status,502);assert.equal(h.sent.length,0)}});
test('expired subscriptions are removed only for the recipient',async()=>{const h=setup({expired:true});await h.call();assert.deepEqual(h.queries.find(q=>q.operation==='delete').filters,[['endpoint','https://web.push.apple.com/test'],['user_id','recipient']])});
test('service worker shows notifications and prevents external navigation',async()=>{const handlers={},shown=[],opened=[];let task;vm.runInNewContext(fs.readFileSync('public/sw.js','utf8'),{URL,self:{location:{origin:'https://www.88esx.com'},addEventListener:(n,fn)=>handlers[n]=fn,registration:{showNotification:async(...a)=>shown.push(a)}},clients:{matchAll:async()=>[],openWindow:async u=>opened.push(u)}});handlers.push({data:{json:()=>({body:'New message',url:'https://evil.test'})},waitUntil:p=>task=p});await task;assert.equal(shown[0][1].data.url,'/account');handlers.notificationclick({notification:{close(){},data:{url:'//evil.test'}},waitUntil:p=>task=p});await task;assert.deepEqual(opened,['https://www.88esx.com/account'])});
