import Image from 'next/image';
import { copy, type Language } from './content';
const beauty: Record<Language, string[]> = {
  ru: ['Корейская косметика: знакомство с K-beauty', 'K-beauty — мир корейской косметики, в котором уход за кожей встречается с макияжем, дизайном упаковки и культурой повседневных ритуалов. Интерес к нему растёт вместе с корейской музыкой, кино и модой, но знакомиться с косметикой можно в своём темпе — без необходимости собирать целую полку средств.', 'Уход как повседневный ритуал', 'В корейской косметике много внимания уделяется текстурам и удобству нанесения: от лёгких водянистых средств до плотных кремов. Тонеры, эссенции и сыворотки различаются по составу и назначению, поэтому название категории не заменяет описание на упаковке. Многоступенчатый уход — известная часть образа K-beauty, но количество баночек само по себе не определяет результат.', 'Форматы, которые узнают во всём мире', 'Тканевые маски, кушоны и тинты стали узнаваемой частью корейской бьюти-культуры. Кушон — компактная упаковка с пропитанной средством подушечкой, а тинт придаёт оттенок губам или щекам. Разные финиши — матовый, сатиновый или сияющий — позволяют менять настроение макияжа. Популярный формат не означает одинаковую формулу: у разных марок свойства могут отличаться.', 'Как выбирать осознанно', 'Начните с того, что вам нужно: удобная текстура, подходящий оттенок или определённый формат. Сравнивайте описание, состав, объём и срок годности, уточняйте способ применения. Красивое оформление и популярность в социальных сетях не гарантируют, что средство подойдёт именно вам. В магазине можно попросить консультанта объяснить различия, а ESX поможет задать вопрос и понять ответ.'],
  en: ['Korean cosmetics: discovering K-beauty', 'K-beauty brings skincare together with makeup, packaging design and everyday rituals. Its cultural appeal sits alongside Korean music, cinema and fashion. You can explore it at your own pace.', 'An everyday ritual', 'Textures range from light watery products to rich creams. Toners, essences and serums differ in ingredients and purpose; read the product description rather than relying on the category name. More steps do not automatically mean better results.', 'Recognizable formats', 'Sheet masks, cushion compacts and lip tints are familiar parts of K-beauty. A cushion holds product in a soaked pad, while tints add color to lips or cheeks. Matte, satin and radiant finishes offer different looks. Formulas vary between brands.', 'Choosing thoughtfully', 'Consider the texture, shade and format you want. Compare ingredients, volume, expiry dates and instructions. Packaging and online popularity do not guarantee a suitable match. Ask a shop consultant about the differences; ESX can help with the conversation.'],
  ko: ['한국 화장품: K-beauty 알아보기', 'K-beauty는 피부 관리, 메이크업, 패키지 디자인과 일상의 습관이 만나는 문화입니다. 음악, 영화, 패션과 함께 관심을 받고 있으며 자신만의 속도로 알아갈 수 있습니다.', '일상의 관리', '가벼운 제형부터 풍부한 크림까지 다양합니다. 토너, 에센스, 세럼은 성분과 목적이 다르므로 제품 설명을 확인해 보세요. 단계가 많다고 결과가 더 좋은 것은 아닙니다.', '친숙한 제품 형태', '시트 마스크, 쿠션, 틴트는 K-beauty의 대표적인 형태입니다. 쿠션은 내용물을 머금은 패드를 사용하고 틴트는 입술이나 볼에 색을 더합니다. 같은 형태라도 브랜드마다 제형이 다릅니다.', '나에게 맞는 선택', '원하는 질감, 색상과 형태를 생각해 보세요. 성분, 용량, 사용기한과 사용법을 비교하세요. 인기와 포장만으로 적합성을 판단할 수는 없습니다. 매장에서 궁금한 점을 물어보고 ESX로 대화를 이어가세요.'],
  zh: ['韩国化妆品：认识K-beauty', 'K-beauty将护肤、彩妆、包装设计与日常习惯相结合。它与韩国音乐、电影和时尚一起受到关注，也可以按照自己的节奏去了解。', '日常护理', '产品质地从清爽水状到丰润乳霜各不相同。爽肤水、精华等产品的成分和用途不同，应阅读具体说明。步骤多并不自动意味着效果更好。', '熟悉的产品形式', '片状面膜、气垫和唇釉是常见的K-beauty产品。气垫通过浸有产品的软垫取用，染色类产品为唇部或面颊增添颜色。不同品牌配方各有差异。', '理性选择', '先考虑需要的质地、颜色与形式，再比较成分、容量、有效期和使用说明。包装和网络热度不保证适合自己。可向店员询问差别，并用ESX帮助交流。'],
  tr: ['Kore kozmetiği: K-beauty ile tanışın', 'K-beauty; cilt bakımı, makyaj, ambalaj tasarımı ve günlük ritüelleri bir araya getirir. Kore müziği, sineması ve modasıyla birlikte ilgi görür.', 'Günlük bakım', 'Hafif dokulardan yoğun kremlere kadar farklı seçenekler vardır. Tonik, esans ve serumların içerikleri ve amaçları değişir. Ürün açıklamasını okuyun; daha çok adım her zaman daha iyi sonuç demek değildir.', 'Tanıdık formatlar', 'Kağıt maskeler, cushion ürünleri ve tintler K-beauty ile özdeşleşir. Cushion, ürün emdirilmiş bir ped içerir; tintler dudaklara veya yanaklara renk verir. Markalar arasında formüller değişir.', 'Bilinçli seçim', 'İstediğiniz doku, renk ve formatı belirleyin. İçerik, miktar, son kullanma tarihi ve talimatları karşılaştırın. Popülerlik uygunluğu garanti etmez. Mağazada soru sorarken ESX iletişime yardımcı olabilir.'],
  vi: ['Mỹ phẩm Hàn Quốc: khám phá K-beauty', 'K-beauty kết hợp chăm sóc da, trang điểm, thiết kế bao bì và thói quen hằng ngày. Bạn có thể tìm hiểu theo nhịp độ riêng.', 'Chăm sóc hằng ngày', 'Kết cấu đa dạng từ dạng nước nhẹ đến kem đặc. Toner, essence và serum khác nhau về thành phần và mục đích. Hãy đọc mô tả sản phẩm; nhiều bước không tự động mang lại kết quả tốt hơn.', 'Những dạng sản phẩm quen thuộc', 'Mặt nạ giấy, cushion và son tint là những dạng phổ biến. Cushion chứa miếng đệm thấm sản phẩm, còn tint tạo màu cho môi hoặc má. Công thức có thể khác nhau giữa các thương hiệu.', 'Lựa chọn có cân nhắc', 'Xác định kết cấu, màu sắc và dạng sản phẩm bạn muốn. So sánh thành phần, dung tích, hạn dùng và hướng dẫn. Bao bì và độ nổi tiếng không bảo đảm phù hợp. ESX có thể giúp bạn trao đổi với nhân viên tư vấn.'],
  km: ['គ្រឿងសម្អាងកូរ៉េ៖ ស្គាល់ K-beauty', 'K-beauty រួមបញ្ចូលការថែស្បែក ការតុបតែងមុខ ការរចនាកញ្ចប់ និងទម្លាប់ប្រចាំថ្ងៃ។ អ្នកអាចស្វែងយល់តាមចំណាប់អារម្មណ៍របស់ខ្លួន។', 'ការថែទាំប្រចាំថ្ងៃ', 'ផលិតផលមានទាំងប្រភេទស្រាល និងក្រែមខាប់។ តូន័រ អេសសិន និងសេរ៉ូមមានគ្រឿងផ្សំ និងគោលបំណងខុសគ្នា។ អានការពិពណ៌នា៖ ជំហានច្រើនមិនមានន័យថាលទ្ធផលល្អជាងជានិច្ចទេ។', 'ទម្រង់ដែលគេស្គាល់', 'ម៉ាសសន្លឹក គូសិន និងផលិតផលពណ៌បបូរមាត់ជាផ្នែកនៃ K-beauty។ គូសិនមានបន្ទះដែលជ្រាបផលិតផល។ រូបមន្តអាចខុសគ្នាតាមម៉ាក។', 'ជ្រើសរើសដោយយកចិត្តទុកដាក់', 'គិតពីសាច់ផលិតផល ពណ៌ និងទម្រង់ដែលអ្នកចង់បាន។ ប្រៀបធៀបគ្រឿងផ្សំ បរិមាណ កាលបរិច្ឆេទផុតកំណត់ និងការណែនាំ។ ភាពល្បីមិនធានាថាសមនឹងអ្នកទេ។ ESX អាចជួយការសន្ទនាជាមួយអ្នកប្រឹក្សា។'],
  kk: ['Корей косметикасы: K-beauty әлемі', 'K-beauty тері күтімін, макияжды, қаптама дизайнын және күнделікті әдеттерді біріктіреді. Онымен өз қарқыныңызбен танысуға болады.', 'Күнделікті күтім', 'Жеңіл сұйықтықтардан қою кремдерге дейін түрлі құрылымдар бар. Тонер, эссенция мен сарысудың құрамы және мақсаты әртүрлі. Өнім сипаттамасын оқыңыз: көп қадам әрдайым жақсы нәтиже бермейді.', 'Таныс пішіндер', 'Маталы маскалар, кушондар мен тинттер K-beauty мәдениетінің бір бөлігі. Кушонда өнім сіңірілген жастықша бар, ал тинт ерінге немесе бетке реңк береді. Әр брендтің формуласы өзгеше болуы мүмкін.', 'Саналы таңдау', 'Қажетті құрылымды, реңкті және пішінді анықтаңыз. Құрамын, көлемін, жарамдылық мерзімі мен қолдану нұсқаулығын салыстырыңыз. Танымалдық сізге сәйкес келетінін білдірмейді. ESX дүкен кеңесшісімен сөйлесуге көмектеседі.'],
};
export default function BeautyStory({ language }: { language: Language }) {
  const t = beauty[language];
  return <article className="korea-story" aria-labelledby="beauty-story-title"><h2 id="beauty-story-title">{t[0]}</h2><p className="korea-story-intro">{t[1]}</p><Image className="korea-story-art" src="/korea-story/beauty-comic.webp" alt={t[0]} width={1800} height={600} sizes="(max-width: 760px) 100vw, 1264px" /><div className="korea-story-columns">{[2, 4, 6].map((n, i) => <section className="korea-story-part" key={n}><span aria-hidden="true">0{i + 1}</span><h3>{t[n]}</h3><p>{t[n + 1]}</p></section>)}</div><div className="source-row"><a href="https://www.korea.net/NewsFocus/Culture/view?articleId=121626" target="_blank" rel="noreferrer">{copy[language][41]} · Korea.net ↗</a></div></article>;
}
