export const languages = [{code:'ru',name:'Русский'},{code:'ko',name:'한국어'},{code:'en',name:'English'},{code:'zh',name:'中文'},{code:'tr',name:'Türkçe'},{code:'vi',name:'Tiếng Việt'},{code:'km',name:'ខ្មែរ'},{code:'kk',name:'Қазақша'}] as const;
export type Language = typeof languages[number]['code'];
const raw: Record<Language,string> = {
ru: `Главная|Южная Корея|О компании|Реклама|Написать нам|Общение без границ|Разные языки. Один разговор.|Знакомьтесь, делитесь историями и открывайте Корею вместе. Ваш следующий разговор начинается здесь.|Начать общение|Открыть Корею|Выберите свой язык|Ваш язык — ваше пространство|Один QR-код|Пригласите собеседника в личный чат|8 языков|Выберите удобный язык сайта|Ближе друг к другу|Новые знакомства начинаются с приветствия|Откройте свою Корею|Традиции, впечатления и места, к которым хочется возвращаться.|Праздники Южной Кореи|Познакомьтесь с культурой через её традиции.|16 мест, которые стоит увидеть|Наша подборка для первого знакомства со страной.|Люди важнее расстояний.|ESX — пространство для знакомства и общения. Мы создаём простой путь от первого приветствия к новому разговору и помогаем открывать Южную Корею вместе.|Ваш бренд. Новые знакомства.|Расскажите о своём кафе, сервисе или проекте людям, которые открывают жизнь в Корее. Здесь можно представить баннеры, партнёрские истории и подборки мест.|Баннер на сайте|Партнёрская история|Подборка мест|Обсудить размещение|Давайте поговорим.|Есть идея, вопрос или предложение? Оставьте сообщение для команды ESX.|Ваше имя|Электронная почта|Сообщение|Сохранить черновик|Это демонстрационная форма: сообщения пока не отправляются. Черновик можно сохранить на этом устройстве.|Черновик сохранён на этом устройстве.|Создаём пространство для общения.|Туристический справочник|На карте|Лунные даты меняются каждый год.|Навигация|Демонстрационные форматы размещения|Люди общаются за столом|Сохранить черновик не удалось. Попробуйте снова.`,
en: `Home|South Korea|About us|Advertising|Contact us|Connection without borders|Different languages. One conversation.|Meet people, share stories and discover Korea together. Your next conversation starts here.|Start a conversation|Discover Korea|Choose your language|Your language. Your space.|One QR code|Invite someone into a private chat|8 languages|Choose the language that feels like home|Closer together|New connections begin with hello|Find your Korea|Traditions, experiences and places to come back to.|South Korean holidays|Discover the culture through its traditions.|16 places worth discovering|Our selection for your first journey through Korea.|People beyond distance.|ESX is a space to meet and connect. We make the first hello simple and help people discover South Korea together.|Your brand. New connections.|Introduce your café, service or project to people discovering life in Korea. Explore banners, partner stories and curated places.|Website banner|Partner story|Curated places|Discuss a placement|Let’s talk.|Have an idea, question or proposal? Leave a message for the ESX team.|Your name|Email address|Message|Save draft|This is a demo form: messages are not sent yet. You can save a draft on this device.|Draft saved on this device.|A space for connection.|Travel guide|View map|Lunar dates change every year.|Navigation|Sample advertising formats|People talking around a table|Could not save your draft. Please try again.`,
ko: `홈|대한민국|회사 소개|광고|문의하기|국경 없는 소통|언어는 달라도, 대화는 하나.|새로운 사람을 만나 이야기를 나누고 한국을 함께 발견하세요. 다음 대화가 여기서 시작됩니다.|대화 시작|한국 둘러보기|언어를 선택하세요|나의 언어, 나의 공간|QR 코드 하나|비공개 채팅에 상대방을 초대하세요|8개 언어|편안한 언어로 사이트를 이용하세요|서로 더 가까이|새로운 만남은 인사에서 시작됩니다|나만의 한국을 발견하세요|전통과 경험, 다시 찾고 싶은 장소들.|한국의 명절과 기념일|전통을 통해 문화를 만나보세요.|꼭 가볼 만한 16곳|한국을 처음 만나는 여행자를 위한 추천.|거리보다 소중한 사람들.|ESX는 만남과 소통의 공간입니다. 첫인사에서 새로운 대화로 이어지는 간편한 길을 만들고 한국을 함께 알아갑니다.|당신의 브랜드, 새로운 만남.|한국 생활을 알아가는 사람들에게 카페, 서비스 또는 프로젝트를 소개하세요. 배너, 파트너 이야기, 장소 추천을 준비할 수 있습니다.|사이트 배너|파트너 이야기|장소 추천|광고 문의|이야기 나눠요.|아이디어나 질문, 제안이 있나요? ESX 팀에 메시지를 남겨주세요.|이름|이메일|메시지|초안 저장|시연용 양식으로 아직 메시지는 전송되지 않습니다. 이 기기에 초안을 저장할 수 있습니다.|이 기기에 초안이 저장되었습니다.|소통을 위한 공간.|여행 안내|지도 보기|음력 날짜는 매년 달라집니다.|탐색|광고 형식 예시|테이블에 둘러앉아 대화하는 사람들|초안을 저장하지 못했습니다. 다시 시도하세요.`,
zh: `首页|韩国|关于我们|广告合作|联系我们|交流无国界|不同语言，同一场对话。|结识朋友，分享故事，一起探索韩国。下一场对话从这里开始。|开始交流|探索韩国|选择语言|你的语言，你的空间|一个二维码|邀请朋友加入私人聊天|8种语言|选择你熟悉的网站语言|让彼此更近|新的相识从问候开始|发现属于你的韩国|传统、体验和令人流连忘返的地方。|韩国节日|通过传统了解文化。|值得一游的16个地方|为初次探索韩国精选的目的地。|距离挡不住相遇。|ESX是相识与交流的空间。我们让第一声问候轻松开启新的对话，并帮助大家一起探索韩国。|你的品牌，新的相遇。|向探索韩国生活的人们介绍你的咖啡馆、服务或项目。可以展示横幅广告、合作故事和精选地点。|网站横幅|合作故事|精选地点|洽谈合作|聊一聊吧。|有想法、问题或建议？给ESX团队留言。|姓名|电子邮箱|留言|保存草稿|这是演示表单，暂不发送消息。你可以在此设备上保存草稿。|草稿已保存在此设备上。|为交流创造空间。|旅游指南|查看地图|农历节日对应的公历日期每年不同。|导航|广告形式示例|围坐在桌旁交谈的人们|无法保存草稿，请重试。`,
tr: `Ana sayfa|Güney Kore|Hakkımızda|Reklam|İletişim|Sınır tanımayan iletişim|Farklı diller. Tek sohbet.|İnsanlarla tanışın, hikâyeler paylaşın ve Kore’yi birlikte keşfedin. Yeni sohbetiniz burada başlıyor.|Sohbet başlat|Kore’yi keşfet|Dilinizi seçin|Sizin diliniz, sizin alanınız|Tek QR kodu|Birini özel sohbete davet edin|8 dil|Siteyi rahat ettiğiniz dilde kullanın|Birbirimize daha yakın|Yeni tanışmalar bir selamla başlar|Kendi Kore’nizi keşfedin|Gelenekler, deneyimler ve dönmek isteyeceğiniz yerler.|Güney Kore bayramları|Gelenekler aracılığıyla kültürü tanıyın.|Görülmeye değer 16 yer|Kore’yle ilk tanışmanız için seçtiklerimiz.|Mesafelerin ötesinde insanlar.|ESX tanışmak ve iletişim kurmak için bir alandır. İlk selamdan yeni bir sohbete uzanan yolu kolaylaştırıyor, Kore’yi birlikte keşfediyoruz.|Markanız. Yeni bağlantılar.|Kore’de yaşamı keşfeden insanlara kafenizi, hizmetinizi veya projenizi tanıtın. Bannerlar, ortaklık hikâyeleri ve yer önerileri sunulabilir.|Site bannerı|Ortaklık hikâyesi|Yer önerileri|Reklamı görüşelim|Konuşalım.|Fikriniz, sorunuz veya öneriniz mi var? ESX ekibine mesaj bırakın.|Adınız|E-posta|Mesaj|Taslağı kaydet|Bu bir demo formudur; mesajlar henüz gönderilmez. Taslağı bu cihaza kaydedebilirsiniz.|Taslak bu cihaza kaydedildi.|İletişim için bir alan.|Gezi rehberi|Haritada gör|Ay takvimi tarihleri her yıl değişir.|Gezinme|Örnek reklam biçimleri|Masa etrafında sohbet eden insanlar|Taslak kaydedilemedi. Yeniden deneyin.`,
vi: `Trang chủ|Hàn Quốc|Về chúng tôi|Quảng cáo|Liên hệ|Kết nối không biên giới|Khác ngôn ngữ. Chung câu chuyện.|Gặp gỡ, chia sẻ câu chuyện và cùng khám phá Hàn Quốc. Cuộc trò chuyện tiếp theo bắt đầu tại đây.|Bắt đầu trò chuyện|Khám phá Hàn Quốc|Chọn ngôn ngữ|Ngôn ngữ của bạn, không gian của bạn|Một mã QR|Mời người khác vào cuộc trò chuyện riêng|8 ngôn ngữ|Chọn ngôn ngữ trang web quen thuộc|Gần nhau hơn|Cuộc gặp mới bắt đầu từ lời chào|Khám phá Hàn Quốc của bạn|Truyền thống, trải nghiệm và những nơi muốn quay lại.|Ngày lễ Hàn Quốc|Tìm hiểu văn hóa qua truyền thống.|16 địa điểm nên ghé thăm|Gợi ý cho hành trình đầu tiên tại Hàn Quốc.|Con người vượt khoảng cách.|ESX là không gian gặp gỡ và kết nối. Chúng tôi giúp lời chào đầu tiên trở thành cuộc trò chuyện mới và cùng bạn khám phá Hàn Quốc.|Thương hiệu của bạn. Kết nối mới.|Giới thiệu quán cà phê, dịch vụ hoặc dự án tới những người khám phá cuộc sống tại Hàn Quốc. Có thể giới thiệu biểu ngữ, câu chuyện đối tác và địa điểm nổi bật.|Biểu ngữ trang web|Câu chuyện đối tác|Địa điểm chọn lọc|Trao đổi quảng cáo|Cùng trò chuyện.|Có ý tưởng, câu hỏi hay đề xuất? Để lại lời nhắn cho đội ngũ ESX.|Tên của bạn|Email|Lời nhắn|Lưu bản nháp|Đây là biểu mẫu mẫu, chưa gửi tin nhắn. Bạn có thể lưu bản nháp trên thiết bị này.|Đã lưu bản nháp trên thiết bị.|Không gian kết nối.|Cẩm nang du lịch|Xem bản đồ|Ngày âm lịch có ngày dương lịch khác nhau mỗi năm.|Điều hướng|Hình thức quảng cáo minh họa|Mọi người trò chuyện quanh bàn|Không thể lưu bản nháp. Vui lòng thử lại.`,
km: `ទំព័រដើម|កូរ៉េខាងត្បូង|អំពីយើង|ផ្សាយពាណិជ្ជកម្ម|ទាក់ទងយើង|ទំនាក់ទំនងគ្មានព្រំដែន|ភាសាខុសគ្នា ការសន្ទនាតែមួយ។|ជួបមនុស្សថ្មី ចែករំលែករឿងរ៉ាវ និងស្វែងយល់ពីកូរ៉េជាមួយគ្នា។|ចាប់ផ្តើមសន្ទនា|ស្វែងយល់ពីកូរ៉េ|ជ្រើសរើសភាសា|ភាសារបស់អ្នក កន្លែងរបស់អ្នក|កូដ QR មួយ|អញ្ជើញម្នាក់ចូលការជជែកឯកជន|៨ ភាសា|ជ្រើសភាសាគេហទំព័រដែលអ្នកស្គាល់|កាន់តែជិតគ្នា|ការស្គាល់គ្នាចាប់ផ្តើមពីការសួរសុខទុក្ខ|ស្វែងរកកូរ៉េរបស់អ្នក|ប្រពៃណី បទពិសោធន៍ និងកន្លែងដែលចង់ត្រឡប់មកវិញ។|ពិធីបុណ្យនៅកូរ៉េខាងត្បូង|ស្វែងយល់វប្បធម៌តាមប្រពៃណី។|១៦ កន្លែងគួរទៅលេង|ជម្រើសសម្រាប់ដំណើរដំបូងនៅកូរ៉េ។|មនុស្សលើសពីចម្ងាយ។|ESX ជាកន្លែងសម្រាប់ជួប និងទំនាក់ទំនង។ យើងធ្វើឱ្យការសួរសុខទុក្ខដំបូងងាយស្រួល និងជួយស្វែងយល់កូរ៉េជាមួយគ្នា។|ម៉ាករបស់អ្នក ទំនាក់ទំនងថ្មី។|ណែនាំហាងកាហ្វេ សេវា ឬគម្រោងរបស់អ្នកដល់អ្នកស្វែងយល់ជីវិតនៅកូរ៉េ តាមបដា រឿងដៃគូ និងកន្លែងជ្រើសរើស។|បដាគេហទំព័រ|រឿងដៃគូ|កន្លែងជ្រើសរើស|ពិភាក្សាការផ្សាយ|តោះនិយាយគ្នា។|មានគំនិត សំណួរ ឬសំណើ? ទុកសារជូនក្រុម ESX។|ឈ្មោះ|អ៊ីមែល|សារ|រក្សាទុកសេចក្តីព្រាង|នេះជាទម្រង់សាកល្បង មិនទាន់ផ្ញើសារទេ។ អ្នកអាចរក្សាសេចក្តីព្រាងលើឧបករណ៍នេះ។|បានរក្សាសេចក្តីព្រាងលើឧបករណ៍នេះ។|កន្លែងសម្រាប់ទំនាក់ទំនង។|មគ្គុទ្ទេសក៍ទេសចរណ៍|មើលផែនទី|កាលបរិច្ឆេទចន្ទគតិប្រែប្រួលរៀងរាល់ឆ្នាំ។|រុករក|គំរូការផ្សាយពាណិជ្ជកម្ម|មនុស្សកំពុងសន្ទនាជុំវិញតុ|មិនអាចរក្សាទុកបានទេ។ សូមព្យាយាមម្តងទៀត។`,
kk: `Басты бет|Оңтүстік Корея|Компания туралы|Жарнама|Бізге жазыңыз|Шекарасыз қарым-қатынас|Тілдер әртүрлі. Әңгіме ортақ.|Танысыңыз, оқиғалармен бөлісіңіз және Кореяны бірге ашыңыз. Келесі әңгімеңіз осы жерден басталады.|Әңгіме бастау|Кореяны ашу|Тілді таңдаңыз|Сіздің тіліңіз, сіздің кеңістігіңіз|Бір QR-код|Әңгімелесушіні жеке чатқа шақырыңыз|8 тіл|Сайттың өзіңізге ыңғайлы тілін таңдаңыз|Бір-бірімізге жақынырақ|Жаңа таныстық сәлемнен басталады|Өз Кореяңызды ашыңыз|Дәстүрлер, әсерлер және қайта оралғыңыз келетін орындар.|Оңтүстік Корея мерекелері|Мәдениетті дәстүрлер арқылы таныңыз.|Көруге тұрарлық 16 орын|Елмен алғаш танысуға арналған таңдауымыз.|Адамдар қашықтықтан маңызды.|ESX — танысу және қарым-қатынас кеңістігі. Біз алғашқы сәлемнен жаңа әңгімеге дейінгі жолды жеңілдетіп, Оңтүстік Кореяны бірге ашуға көмектесеміз.|Сіздің брендіңіз. Жаңа таныстықтар.|Кореядағы өмірді танып жатқан адамдарға кафеңізді, қызметіңізді немесе жобаңызды таныстырыңыз. Баннерлер, серіктес әңгімелері және орындар топтамасын ұсынуға болады.|Сайт баннері|Серіктес әңгімесі|Орындар топтамасы|Жарнаманы талқылау|Сөйлесейік.|Идеяңыз, сұрағыңыз немесе ұсынысыңыз бар ма? ESX тобына хабарлама қалдырыңыз.|Атыңыз|Электрондық пошта|Хабарлама|Нобайды сақтау|Бұл — үлгі нысан, хабарламалар әзірге жіберілмейді. Нобайды осы құрылғыда сақтай аласыз.|Нобай осы құрылғыда сақталды.|Қарым-қатынас кеңістігі.|Саяхат анықтамалығы|Картадан көру|Ай күнтізбесінің күндері жыл сайын өзгереді.|Шарлау|Жарнама үлгілері|Үстел басында сөйлесіп отырған адамдар|Нобай сақталмады. Қайта көріңіз.`
};
export const copy = Object.fromEntries(Object.entries(raw).map(([k,v])=>[k,v.split('|')])) as Record<Language,string[]>;
export const holidays: Record<Language,string[]> = {
ru:['Соллаль~Лунный Новый год. Семьи собираются вместе, чтят старших и едят суп ттоккук.','Самильчоль · 1 марта~День памяти движения за независимость, начавшегося в 1919 году.','День детей · 5 мая~Семейный праздник с подарками, прогулками и развлечениями для детей.','День рождения Будды~Храмы украшают цветными фонарями. Отмечается в восьмой день четвёртого лунного месяца.','Чхусок~Праздник урожая: встречи с семьёй, память о предках и рисовые пирожки сонпхён.','День хангыля · 9 октября~Праздник корейского алфавита и культурного наследия короля Седжона.'],
en:['Seollal~Lunar New Year with family gatherings, respect for elders and tteokguk rice cake soup.','Independence Movement Day · March 1~Commemorates the Korean independence movement that began in 1919.','Children’s Day · May 5~A family celebration with gifts, outings and activities for children.','Buddha’s Birthday~Temples display colorful lanterns on the eighth day of the fourth lunar month.','Chuseok~A harvest celebration with family reunions, ancestral remembrance and songpyeon rice cakes.','Hangul Day · October 9~Celebrates the Korean alphabet and the cultural legacy of King Sejong.'],
ko:['설날~가족이 모여 어른께 세배하고 떡국을 먹는 음력 새해 명절입니다.','삼일절 · 3월 1일~1919년에 시작된 독립운동을 기념하는 날입니다.','어린이날 · 5월 5일~선물과 나들이로 어린이의 행복을 함께 기리는 날입니다.','부처님 오신 날~음력 4월 8일, 사찰을 형형색색의 연등으로 장식합니다.','추석~가족이 모여 조상을 기리고 송편을 나누는 수확의 명절입니다.','한글날 · 10월 9일~한글과 세종대왕의 문화적 유산을 기념합니다.'],
zh:['春节~农历新年，家人团聚、向长辈拜年并享用年糕汤。','三一节 · 3月1日~纪念1919年开始的韩国独立运动。','儿童节 · 5月5日~为孩子准备礼物、出游和活动的家庭节日。','佛诞节~农历四月初八，寺庙挂起彩色灯笼。','秋夕~家人团聚、祭祖并分享松饼的丰收节日。','韩文日 · 10月9日~纪念韩文字母及世宗大王的文化遗产。'],
tr:['Seollal~Ay takvimine göre yeni yıl; aile buluşmaları, büyüklere saygı ve tteokguk çorbası.','Bağımsızlık Hareketi Günü · 1 Mart~1919’da başlayan Kore bağımsızlık hareketini anar.','Çocuk Bayramı · 5 Mayıs~Çocuklara hediyeler, geziler ve etkinliklerle kutlanan aile bayramı.','Buda’nın Doğum Günü~Dördüncü ay ayının sekizinci gününde tapınaklar renkli fenerlerle süslenir.','Chuseok~Aile buluşmaları, ataları anma ve songpyeon pirinç tatlılarıyla hasat bayramı.','Hangul Günü · 9 Ekim~Kore alfabesini ve Kral Sejong’un kültürel mirasını kutlar.'],
vi:['Seollal~Tết âm lịch, gia đình đoàn tụ, chúc thọ người lớn và ăn canh bánh gạo tteokguk.','Ngày Phong trào Độc lập · 1/3~Tưởng niệm phong trào độc lập Hàn Quốc bắt đầu năm 1919.','Ngày Thiếu nhi · 5/5~Ngày gia đình với quà tặng, đi chơi và hoạt động dành cho trẻ em.','Phật đản~Ngày 8 tháng 4 âm lịch, các chùa trang trí đèn lồng nhiều màu.','Chuseok~Lễ mùa gặt với đoàn tụ gia đình, tưởng nhớ tổ tiên và bánh songpyeon.','Ngày Hangul · 9/10~Tôn vinh bảng chữ cái Hàn Quốc và di sản văn hóa của vua Sejong.'],
km:['សូលឡាល់~ចូលឆ្នាំចន្ទគតិ ជួបជុំគ្រួសារ គោរពចាស់ទុំ និងញ៉ាំស៊ុបនំអង្ករ។','ទិវាចលនាឯករាជ្យ · ១ មីនា~រំលឹកចលនាឯករាជ្យកូរ៉េដែលចាប់ផ្តើមក្នុងឆ្នាំ ១៩១៩។','ទិវាកុមារ · ៥ ឧសភា~ថ្ងៃគ្រួសារ មានអំណោយ ដំណើរកម្សាន្ត និងសកម្មភាពកុមារ។','ថ្ងៃប្រសូតព្រះពុទ្ធ~ថ្ងៃទី៨ ខែទី៤ ចន្ទគតិ វត្តតុបតែងដោយចង្កៀងចម្រុះពណ៌។','ឈូសុក~បុណ្យប្រមូលផល ជួបជុំគ្រួសារ រំលឹកដូនតា និងញ៉ាំនំអង្ករ។','ទិវាហាន់ហ្គុល · ៩ តុលា~អបអរអក្សរកូរ៉េ និងបេតិកភណ្ឌវប្បធម៌របស់ព្រះបាទសេជុង។'],
kk:['Соллаль~Ай күнтізбесі бойынша жаңа жыл. Отбасылар жиналып, үлкендерге құрмет көрсетіп, ттоккук сорпасын ішеді.','Тәуелсіздік қозғалысы күні · 1 наурыз~1919 жылы басталған Корея тәуелсіздік қозғалысын еске алу күні.','Балалар күні · 5 мамыр~Балаларға сыйлықтар, серуендер мен ойындар арналған отбасылық мереке.','Будданың туған күні~Ай күнтізбесінің төртінші айының сегізінші күні ғибадатханалар түрлі түсті шамдармен безендіріледі.','Чхусок~Отбасымен жиналып, ата-бабаларды еске алып, сонпхён күріш тәттісін бөлісетін өнім мерекесі.','Хангыль күні · 9 қазан~Корей әліпбиі мен Седжон патшаның мәдени мұрасына арналған күн.']
};
export const placeNames: Record<Language,string> = {
ru:'Дворец Кёнбоккун|Дворец Чхандоккун|Башня N Seoul|Ручей Чхонгечхон|Национальный музей Кореи|Сеульский лес|Парки реки Ханган|Район Хондэ|Сонгдо Central Park|Крепость Хвасон|Храм Пульгукса|Деревня Камчхон|Пляж Хэундэ|Храм Хэдон Ёнгунса|Гора Халласан|Пик Сонсан Ильчхульбон',
en:'Gyeongbokgung Palace|Changdeokgung Palace|N Seoul Tower|Cheonggyecheon Stream|National Museum of Korea|Seoul Forest|Hangang Parks|Hongdae|Songdo Central Park|Suwon Hwaseong Fortress|Bulguksa Temple|Gamcheon Culture Village|Haeundae Beach|Haedong Yonggungsa Temple|Hallasan Mountain|Seongsan Ilchulbong',
ko:'경복궁|창덕궁|N서울타워|청계천|국립중앙박물관|서울숲|한강공원|홍대|송도 센트럴파크|수원 화성|불국사|감천문화마을|해운대해수욕장|해동용궁사|한라산|성산일출봉',
zh:'景福宫|昌德宫|N首尔塔|清溪川|韩国国立中央博物馆|首尔林|汉江公园|弘大|松岛中央公园|水原华城|佛国寺|甘川文化村|海云台海水浴场|海东龙宫寺|汉拿山|城山日出峰',
tr:'Gyeongbokgung Sarayı|Changdeokgung Sarayı|N Seul Kulesi|Cheonggyecheon Deresi|Kore Ulusal Müzesi|Seul Ormanı|Hangang Parkları|Hongdae|Songdo Merkez Parkı|Suwon Hwaseong Kalesi|Bulguksa Tapınağı|Gamcheon Kültür Köyü|Haeundae Plajı|Haedong Yonggungsa Tapınağı|Hallasan Dağı|Seongsan Ilchulbong',
vi:'Cung điện Gyeongbokgung|Cung điện Changdeokgung|Tháp N Seoul|Suối Cheonggyecheon|Bảo tàng Quốc gia Hàn Quốc|Rừng Seoul|Công viên sông Hàn|Hongdae|Công viên trung tâm Songdo|Pháo đài Hwaseong|Chùa Bulguksa|Làng văn hóa Gamcheon|Bãi biển Haeundae|Chùa Haedong Yonggungsa|Núi Hallasan|Đỉnh Seongsan Ilchulbong',
km:'ព្រះបរមរាជវាំងក្យុងបុកគុង|ព្រះរាជវាំងឆាងដុកគុង|ប៉ម N សេអ៊ូល|ស្ទឹងឆុងគ្យេឆុន|សារមន្ទីរជាតិកូរ៉េ|ព្រៃសេអ៊ូល|ឧទ្យានទន្លេហាន|ហុងដេ|ឧទ្យានកណ្តាលសុងដូ|បន្ទាយហ្វាសុង|វត្តប៊ុលហ្គុកសា|ភូមិវប្បធម៌កាំឆុន|ឆ្នេរហេអ៊ុនដេ|វត្តហេដុងយ៉ុងគុងសា|ភ្នំហាល់ឡាសាន|កំពូលភ្នំសុងសានអ៊ីលឈុលបុង',
kk:'Кёнбоккун сарайы|Чхандоккун сарайы|N Сеул мұнарасы|Чхонгечхон бұлағы|Корея ұлттық мұражайы|Сеул орманы|Ханган саябақтары|Хондэ ауданы|Сонгдо орталық саябағы|Хвасон қамалы|Пульгукса ғибадатханасы|Камчхон мәдени ауылы|Хэундэ жағажайы|Хэдон Ёнгунса ғибадатханасы|Халласан тауы|Сонсан Ильчхульбон шыңы'
};
