import Image from 'next/image';
import { type Language } from './content';

const messages: Record<Language, string> = {
  ru: 'ESX поможет вам|От первого знакомства до важных вопросов — начните разговор через личный чат.|Просто знакомство|Познакомьтесь с новым человеком, обменяйтесь QR-кодом и продолжите общение в личном чате.|Ресторан|Обсудите меню с сотрудником, уточните состав блюда и пожелания к заказу.|Гостиница|Свяжитесь с персоналом, задайте вопросы о заселении и расскажите о своих пожеланиях.|Бизнес|Начните разговор с партнёром, обсудите идеи и договоритесь о следующей встрече.|Банк|Задайте сотруднику вопросы об услугах, документах и порядке обслуживания.',
  en: 'ESX can help you|From a first hello to important questions — start a conversation in a private chat.|Meeting someone new|Meet someone, share a QR code and keep talking in a private chat.|Restaurant|Discuss the menu with staff, ask about ingredients and explain your preferences.|Hotel|Contact staff, ask about check-in and share your requests.|Business|Connect with a partner, discuss ideas and arrange your next meeting.|Bank|Ask staff about services, documents and the steps to follow.',
  ko: 'ESX가 도와드릴게요|첫 인사부터 중요한 질문까지, 개인 채팅으로 대화를 시작하세요.|새로운 만남|새로운 사람과 QR 코드를 공유하고 개인 채팅으로 대화를 이어가세요.|레스토랑|직원에게 메뉴와 재료를 물어보고 주문 시 원하는 사항을 전하세요.|호텔|직원에게 체크인을 문의하고 필요한 사항을 전달하세요.|비즈니스|파트너와 아이디어를 나누고 다음 미팅을 정하세요.|은행|직원에게 서비스, 필요 서류와 이용 절차를 문의하세요.',
  zh: 'ESX为您提供帮助|从初次问候到重要问题，通过私密聊天开始交流。|结识新朋友|认识新朋友，分享二维码，在私密聊天中继续交流。|餐厅|与员工讨论菜单，询问食材并说明点餐偏好。|酒店|联系员工，咨询入住事宜并提出您的需求。|商务|与合作伙伴交流想法，安排下一次会面。|银行|向员工咨询服务、所需文件和办理流程。',
  tr: 'ESX size yardımcı olur|İlk merhabadan önemli sorulara, özel sohbette iletişim kurun.|Yeni tanışmalar|Yeni biriyle tanışın, QR kod paylaşın ve özel sohbette konuşmaya devam edin.|Restoran|Personelle menüyü konuşun, malzemeleri sorun ve sipariş tercihlerinizi belirtin.|Otel|Personelle iletişime geçin, giriş hakkında soru sorun ve isteklerinizi iletin.|İş dünyası|Bir ortakla fikirlerinizi paylaşın ve sonraki görüşmeyi planlayın.|Banka|Personele hizmetler, belgeler ve işlemler hakkında soru sorun.',
  vi: 'ESX giúp bạn|Từ lời chào đầu tiên đến câu hỏi quan trọng, hãy bắt đầu bằng trò chuyện riêng.|Làm quen|Gặp người mới, chia sẻ mã QR và tiếp tục trò chuyện riêng.|Nhà hàng|Trao đổi về thực đơn, hỏi thành phần món ăn và nêu yêu cầu khi gọi món.|Khách sạn|Liên hệ nhân viên, hỏi về nhận phòng và nêu nhu cầu của bạn.|Kinh doanh|Trao đổi ý tưởng với đối tác và hẹn cuộc gặp tiếp theo.|Ngân hàng|Hỏi nhân viên về dịch vụ, giấy tờ và thủ tục.',
  km: 'ESX អាចជួយអ្នក|ពីការសួរសុខទុក្ខដំបូងដល់សំណួរសំខាន់ ចាប់ផ្តើមតាមការជជែកឯកជន។|ស្គាល់មិត្តថ្មី|ស្គាល់មនុស្សថ្មី ចែករំលែកកូដ QR ហើយបន្តការជជែកឯកជន។|ភោជនីយដ្ឋាន|ពិភាក្សាមុខម្ហូប សួរគ្រឿងផ្សំ និងប្រាប់បុគ្គលិកពីតម្រូវការរបស់អ្នក។|សណ្ឋាគារ|ទាក់ទងបុគ្គលិក សួរអំពីការចូលស្នាក់នៅ និងប្រាប់តម្រូវការរបស់អ្នក។|អាជីវកម្ម|ពិភាក្សាគំនិតជាមួយដៃគូ និងកំណត់ការជួបលើកក្រោយ។|ធនាគារ|សួរបុគ្គលិកអំពីសេវាកម្ម ឯកសារ និងនីតិវិធី។',
  kk: 'ESX сізге көмектеседі|Алғашқы сәлемнен маңызды сұрақтарға дейін — жеке чатта әңгіме бастаңыз.|Жай танысу|Жаңа адаммен танысып, QR кодпен бөлісіңіз және жеке чатта сөйлесуді жалғастырыңыз.|Мейрамхана|Қызметкермен мәзірді талқылап, тағам құрамын сұраңыз және тапсырысқа тілектеріңізді айтыңыз.|Қонақүй|Қызметкерлермен байланысып, тіркелу туралы сұраңыз және өтініштеріңізді жеткізіңіз.|Бизнес|Серіктеспен идеяларды талқылап, келесі кездесуді белгілеңіз.|Банк|Қызметкерден қызметтер, құжаттар және рәсімдер туралы сұраңыз.',
};

const scenes = ['meeting-people', 'restaurant', 'hotel', 'business', 'bank'];
const details: Record<Language, string[]> = {
  ru: [
    'Иногда всё начинается с простого «привет»: на прогулке, в поездке или за соседним столиком. Покажите QR-код, пригласите собеседника в ESX и расскажите немного о себе. В чате можно обсудить общие интересы и договориться, где встретиться снова.',
    'В незнакомом месте бывает непросто объяснить, какое блюдо вы хотите попробовать. Начните чат с сотрудником и задавайте вопросы по порядку: насколько острое блюдо, что входит в состав и можно ли изменить гарнир. Так у разговора появится удобное место на экране.',
    'После дороги хочется спокойно разобраться с бытовыми вопросами. В разговоре с сотрудником можно уточнить время завтрака, спросить о багаже или попросить дополнительное полотенце. Запишите свой вопрос в ESX и обсудите детали заселения без спешки.',
    'Хорошее сотрудничество начинается с понятного разговора. Используйте личный чат, чтобы представиться, описать свою идею и задать партнёру уточняющие вопросы. Обсудите удобное время встречи и запишите следующие шаги в сообщениях.',
    'Когда вы приходите в отделение, полезно сначала объяснить, с каким вопросом обращаетесь. Через чат можно спросить сотрудника, какие документы понадобятся и к кому подойти. Если ответ непонятен, уточните один пункт за другим и обсудите порядок действий.'
  ],
  en: ['A simple hello on a walk or a trip can start a new connection. Share a QR code, introduce yourself in ESX and talk about common interests or your next meeting.', 'In an unfamiliar restaurant, use the chat to ask how spicy a dish is, what ingredients it contains or whether a side dish can be changed. Discuss each detail with staff at your own pace.', 'After a journey, ask staff about breakfast, luggage or an extra towel. Write your question in ESX and discuss the details of your stay.', 'Introduce yourself, explain your idea and ask your partner follow-up questions. Use messages to discuss a meeting time and outline your next steps together.', 'Explain the reason for your visit and ask staff which documents you need or whom to speak to. Clarify each point in the chat and discuss what to do next.'],
  ko: ['산책이나 여행 중 건넨 인사가 새로운 만남으로 이어집니다. QR 코드를 공유하고 ESX에서 자기소개와 관심사를 나누며 다음 만남을 이야기하세요.', '낯선 식당에서는 맵기, 재료, 곁들임 변경 여부를 채팅으로 물어보세요. 직원과 하나씩 차분하게 확인할 수 있습니다.', '여행 후에는 조식 시간, 짐 보관, 추가 수건을 문의할 수 있습니다. ESX에 질문을 적고 숙박에 필요한 내용을 직원과 이야기하세요.', '자신을 소개하고 아이디어를 설명하며 파트너에게 궁금한 점을 물어보세요. 메시지로 미팅 시간과 다음 단계를 함께 정하세요.', '방문 목적을 설명하고 필요한 서류나 담당자를 물어보세요. 이해하기 어려운 부분은 채팅으로 하나씩 확인하세요.'],
  zh: ['散步或旅行中的一句问候也能开启新的相识。分享二维码，在ESX中介绍自己，聊聊共同兴趣和下次见面的安排。', '在陌生的餐厅，通过聊天询问辣度、食材或能否更换配菜。按照自己的节奏与员工逐项沟通。', '旅途之后，可以询问早餐时间、行李寄存或额外的毛巾。在ESX中写下问题，与员工讨论住宿细节。', '介绍自己，说明想法，并向合作伙伴进一步提问。通过消息商量会面时间和接下来的步骤。', '说明来访目的，向员工询问需要哪些文件或应联系谁。不明白的地方可以在聊天中逐项确认。'],
  tr: ['Yürüyüşte veya yolculukta bir merhaba yeni bir tanışmaya dönüşebilir. QR kod paylaşın, kendinizi tanıtın ve ortak ilgi alanlarınızı konuşun.', 'Yemeğin acılığını, malzemelerini veya garnitür değişikliğini sohbette sorun. Ayrıntıları personelle adım adım konuşun.', 'Kahvaltı, bagaj veya ek havlu hakkında soru sorun. ESX üzerinden konaklamanızın ayrıntılarını personelle görüşün.', 'Kendinizi tanıtın, fikrinizi anlatın ve sorularınızı sorun. Mesajlarda toplantı saatini ve sonraki adımları birlikte belirleyin.', 'Ziyaret nedeninizi açıklayın ve gerekli belgeleri veya ilgili görevliyi sorun. Anlaşılmayan noktaları tek tek netleştirin.'],
  vi: ['Một lời chào khi đi dạo hay du lịch có thể mở đầu tình bạn. Chia sẻ mã QR, giới thiệu bản thân và trò chuyện về sở thích chung.', 'Hỏi độ cay, nguyên liệu hoặc việc đổi món ăn kèm qua chat. Trao đổi từng chi tiết với nhân viên theo nhịp của bạn.', 'Hỏi giờ ăn sáng, gửi hành lý hay xin thêm khăn. Viết câu hỏi trong ESX và trao đổi chi tiết lưu trú với nhân viên.', 'Giới thiệu bản thân, trình bày ý tưởng và đặt câu hỏi. Thống nhất giờ gặp và các bước tiếp theo qua tin nhắn.', 'Nêu lý do đến ngân hàng, hỏi giấy tờ cần mang và người phụ trách. Làm rõ từng điều chưa hiểu trong chat.'],
  km: ['ការសួរសុខទុក្ខពេលដើរលេងអាចចាប់ផ្តើមមិត្តភាពថ្មី។ ចែករំលែកកូដ QR ណែនាំខ្លួន និងនិយាយពីចំណូលចិត្តរួម។', 'សួរអំពីកម្រិតហឹរ គ្រឿងផ្សំ ឬការប្តូរម្ហូបបន្ថែមតាមការជជែក។ ពិភាក្សាព័ត៌មាននីមួយៗជាមួយបុគ្គលិក។', 'សួរម៉ោងអាហារពេលព្រឹក ការផ្ញើវ៉ាលី ឬសុំកន្សែងបន្ថែម។ សរសេរសំណួរក្នុង ESX ដើម្បីពិភាក្សាអំពីការស្នាក់នៅ។', 'ណែនាំខ្លួន ពន្យល់គំនិត និងសួរដៃគូ។ កំណត់ម៉ោងជួប និងជំហានបន្ទាប់តាមសារ។', 'ប្រាប់មូលហេតុដែលមក ហើយសួរអំពីឯកសារចាំបាច់ និងបុគ្គលិកទទួលបន្ទុក។ សួរបញ្ជាក់ចំណុចដែលមិនយល់ម្តងមួយៗ។'],
  kk: ['Серуендегі немесе сапардағы сәлем жаңа таныстыққа бастайды. QR кодпен бөлісіп, өзіңізді таныстырыңыз және ортақ қызығушылықтарды талқылаңыз.', 'Чатта тағамның ащылығын, құрамын немесе гарнирді ауыстыру мүмкіндігін сұраңыз. Қызметкермен әр бөлшекті асықпай талқылаңыз.', 'Таңғы ас уақыты, жүк сақтау немесе қосымша сүлгі туралы сұраңыз. ESX арқылы тұруға қатысты сұрақтарды қызметкермен талқылаңыз.', 'Өзіңізді таныстырып, идеяңызды түсіндіріңіз және сұрақтарыңызды қойыңыз. Хабарламаларда кездесу уақытын және келесі қадамдарды келісіңіз.', 'Келу себебін түсіндіріп, қажетті құжаттар мен жауапты қызметкерді сұраңыз. Түсініксіз тұстарды чатта біртіндеп анықтаңыз.'],
};

export default function HelpSection({ language }: { language: Language }) {
  const text = messages[language].split('|');
  return <section className="help-section" aria-labelledby="help-title">
    <div className="help-heading"><div className="eyebrow blue-ink">ESX / 01 — 05</div><h2 id="help-title">{text[0]}</h2><p>{text[1]}</p></div>
    <div className="help-articles">{scenes.map((scene, index) => <article className="help-article" key={scene}>
      <div className="help-illustration"><Image src={`/help-comics/${scene}.webp`} alt={text[2 + index * 2]} width={1536} height={1024} sizes="(max-width: 760px) calc(100vw - 32px), (max-width: 1328px) 48vw, 580px" /></div>
      <div className="help-article-copy"><span className="help-number" aria-hidden="true">ESX / 0{index + 1}</span><h3>{text[2 + index * 2]}</h3><p className="help-lead">{text[3 + index * 2]}</p><p>{details[language][index]}</p></div>
    </article>)}</div>
  </section>;
}
