import Image from 'next/image';
import { copy, type Language } from './content';

type AnimalArticle = [title: string, intro: string, tradition: string, detail: string];
const articles: Record<Language, AnimalArticle[]> = {
  ru: [
    ['Сорока: вестница добрых новостей', '까치 · Ккачхи. В корейской традиции сорока связана с радостью и хорошими вестями. Эта знакомая птица стала выразительным персонажем народной живописи минхва.', 'Один из известных сюжетов — сорока и тигр рядом с сосной. Птица сидит на ветке, а тигр находится внизу. В таких картинах сороку связывают с радостью, сосну — с долголетием, а тигра — с защитой от бед. Вместе они превращают обычную сцену из мира животных в пожелание благополучия.', 'У этого сюжета есть и сатирическое прочтение: маленькая сорока и сильный тигр могут напоминать о взаимоотношениях простого человека и власти. Поэтому стоит присмотреться к их позам и выражениям: картина бывает не только торжественной, но и смешной. Единственного значения у всех подобных работ нет.'],
    ['Медведь: история Уннё и начало легенды', '곰 · Ком. В корейской культуре образ медведя связан прежде всего с Уннё — медведицей, которая, согласно мифу, стала женщиной и матерью Тангуна.', 'В известной версии предания медведь и тигр попросили Хвануна превратить их в людей. Он дал им полынь и чеснок и велел избегать солнечного света сто дней. Тигр не выдержал испытания, а медведица выполнила условие и обрела человеческий облик. Её стали называть Уннё — «женщина-медведь».', 'Позднее Уннё и Хванун стали родителями Тангуна, легендарного основателя Кочосона. Это миф о происхождении, а не документальная биография. Через него можно познакомиться с представлениями о связи небесного и земного мира, превращении и появлении человеческого сообщества.'],
    ['Тигр: хранитель гор и герой корейского искусства', '호랑이 · Хоранъи. Тигр — один из самых узнаваемых животных образов Кореи. Его изображали грозным защитником, спутником горного духа и забавным героем народных картин.', 'В традиционной культуре сила тигра связывалась с защитой от несчастий. На изображениях горного духа сансина он появляется рядом с божеством. Но в народной живописи минхва тигр может выглядеть почти добродушным или комичным: крупные глаза и необычная мимика показывают, насколько разным бывает этот персонаж.', 'Образ продолжает жить в современной культуре. Тигр Ходори стал талисманом Олимпиады в Сеуле 1988 года, а белый тигр Сухоран — зимней Олимпиады в Пхёнчхане 2018 года. Так знакомый герой традиционного искусства получил новую роль — приветствовать гостей со всего мира.'],
  ],
  en: [
    ['Magpie: a bearer of good news', '까치 · Kkachi. In Korean tradition, the magpie is associated with joy and good news. It is a familiar character in minhwa folk painting.', 'A well-known composition pairs a magpie with a tiger and a pine tree. The bird represents joy, the pine longevity, and the tiger protection against misfortune. Together they can express wishes for well-being.', 'Some interpretations also see social satire in the small bird facing a powerful tiger. Look at their expressions and poses: these paintings can be humorous as well as auspicious, and their meanings vary.'],
    ['Bear: Ungnyeo and the founding myth', '곰 · Gom. The bear is closely connected with Ungnyeo, the bear-woman who becomes the mother of Dangun in Korean mythology.', 'In a familiar version, a bear and a tiger ask Hwanung to make them human. He gives them mugwort and garlic and tells them to avoid sunlight for one hundred days. The tiger gives up; the bear succeeds and becomes Ungnyeo.', 'Ungnyeo and Hwanung later become the parents of Dangun, the legendary founder of Gojoseon. This is a foundation myth rather than a documented biography, exploring transformation and the relationship between heaven and the human world.'],
    ['Tiger: mountain guardian and cultural icon', '호랑이 · Horangi. Korean art presents the tiger as a protector, a companion of the mountain spirit and sometimes a comical character.', 'Tiger imagery was used to ward off misfortune. In paintings of Sansin, the mountain spirit, the animal accompanies the deity. In minhwa, large eyes and expressive faces can instead give it an approachable or humorous appearance.', 'The tradition continues in modern mascots: Hodori represented the Seoul 1988 Olympics, and the white tiger Soohorang represented the PyeongChang 2018 Winter Olympics.'],
  ],
  ko: [
    ['까치: 반가운 소식을 전하는 새', '까치는 한국 전통문화에서 기쁨과 좋은 소식을 상징합니다. 민화에서도 친숙한 주인공으로 등장합니다.', '까치와 호랑이, 소나무를 함께 그린 까치호랑이 그림이 대표적입니다. 까치는 기쁨, 소나무는 장수, 호랑이는 액을 막는 의미로 해석되며 행복을 바라는 마음을 전합니다.', '작은 까치와 힘센 호랑이의 관계를 풍자로 읽기도 합니다. 표정과 자세를 살펴보면 익살스러운 모습이 보입니다. 모든 작품이 하나의 뜻만 가진 것은 아닙니다.'],
    ['곰: 웅녀와 단군 이야기', '곰은 사람이 되어 단군의 어머니가 된 웅녀 이야기와 깊이 연결되어 있습니다.', '널리 알려진 신화에서 곰과 호랑이는 환웅에게 사람이 되게 해 달라고 빕니다. 환웅은 쑥과 마늘을 주며 백 일 동안 햇빛을 보지 말라고 합니다. 호랑이는 견디지 못하지만 곰은 여자가 되어 웅녀라 불립니다.', '웅녀와 환웅 사이에서 고조선의 시조로 전해지는 단군이 태어납니다. 이는 역사적 인물의 실증적 전기가 아니라 건국신화입니다. 하늘과 땅의 연결, 변신과 공동체의 시작을 담고 있습니다.'],
    ['호랑이: 산의 수호자에서 문화 상징으로', '호랑이는 한국 미술에서 용맹한 수호자, 산신의 동반자, 때로는 익살스러운 인물로 등장합니다.', '호랑이 그림에는 액을 물리치려는 뜻이 담겼습니다. 산신도에서는 산신 곁에 있지만 민화에서는 큰 눈과 재미있는 표정으로 친근하게 표현되기도 합니다.', '현대에도 이 이미지는 이어집니다. 1988년 서울올림픽의 호돌이와 2018년 평창동계올림픽의 백호 수호랑은 세계의 방문객을 맞이한 마스코트입니다.'],
  ],
  zh: [
    ['喜鹊：传递好消息的鸟', '까치 · Kkachi。在韩国传统文化中，喜鹊象征喜悦和好消息，也是民画中的常见角色。', '喜鹊、老虎和松树经常出现在同一幅画中。喜鹊代表喜悦，松树象征长寿，老虎则有驱邪避祸的含义，共同传达美好的祝愿。', '有些解读还认为，小喜鹊与强大老虎之间的关系包含社会讽刺。观察它们的神态和姿势，可以发现幽默的一面；不同作品的含义并不完全相同。'],
    ['熊：熊女与檀君神话', '곰 · Gom。熊的形象与熊女密切相关。在韩国神话中，她由熊变成人，成为檀君的母亲。', '在广为流传的版本中，熊和老虎请求桓雄让它们变成人。桓雄给它们艾草和大蒜，要求百日不见阳光。老虎未能坚持，熊则成功变成了熊女。', '熊女与桓雄后来生下檀君，即传说中的古朝鲜创建者。这是建国神话，而非经过史料证实的人物传记，讲述了天地相连、变形与人类共同体的起源。'],
    ['老虎：山林守护者与文化象征', '호랑이 · Horangi。在韩国艺术中，老虎既是守护者和山神的伙伴，也可以是诙谐的角色。', '虎画曾被赋予驱邪避祸的意义。山神图中，老虎陪伴在山神身边；而在民画里，大眼睛和生动的表情又使它显得亲切可爱。', '这一形象也延续到现代：虎多利是1988年首尔奥运会吉祥物，白虎Soohorang则是2018年平昌冬奥会吉祥物。'],
  ],
  tr: [
    ['Saksağan: güzel haberlerin habercisi', '까치 · Kkachi. Kore geleneğinde saksağan sevinç ve iyi haberlerle ilişkilendirilir. Minhwa halk resimlerinde sık görülen bir karakterdir.', 'Saksağan, kaplan ve çam ağacını bir araya getiren resimlerde kuş sevinci, çam uzun ömrü, kaplan ise kötülüklerden korunmayı temsil edebilir.', 'Küçük kuş ile güçlü kaplanın ilişkisi bazen toplumsal hiciv olarak da yorumlanır. Yüz ifadelerine ve duruşlarına bakın: her resim aynı anlamı taşımaz.'],
    ['Ayı: Ungnyeo ve kuruluş efsanesi', '곰 · Gom. Ayı, Kore mitolojisinde insana dönüşerek Dangun’un annesi olan Ungnyeo ile bağlantılıdır.', 'Bilinen anlatıda ayı ve kaplan, Hwanung’dan kendilerini insana dönüştürmesini ister. Hwanung onlara pelin otu ve sarımsak verir; yüz gün güneşten uzak durmalarını söyler. Kaplan vazgeçer, ayı ise Ungnyeo adlı kadına dönüşür.', 'Ungnyeo ve Hwanung’un oğlu Dangun, Gojoseon’un efsanevi kurucusudur. Bu anlatı belgelenmiş bir biyografi değil, gök ile insan dünyasının ilişkisini ve dönüşümü konu alan bir kuruluş mitidir.'],
    ['Kaplan: dağların koruyucusu', '호랑이 · Horangi. Kore sanatında kaplan bir koruyucu, dağ ruhunun yoldaşı veya mizahi bir karakter olabilir.', 'Kaplan resimleri talihsizlikleri uzaklaştırma düşüncesiyle kullanılmıştır. Sansin tasvirlerinde tanrının yanında görülürken minhwa resimlerinde iri gözleri ve komik ifadeleriyle daha sevimli görünebilir.', 'Bu gelenek modern maskotlarda da yaşar: Hodori, 1988 Seul Olimpiyatları’nın; beyaz kaplan Soohorang ise 2018 PyeongChang Kış Olimpiyatları’nın maskotudur.'],
  ],
  vi: [
    ['Chim ác là: sứ giả của tin vui', '까치 · Kkachi. Trong truyền thống Hàn Quốc, chim ác là gắn với niềm vui và tin tốt lành. Đây là nhân vật quen thuộc trong tranh dân gian minhwa.', 'Một bố cục nổi tiếng kết hợp chim ác là, hổ và cây thông. Chim tượng trưng cho niềm vui, thông cho sự trường thọ, còn hổ mang ý nghĩa xua đuổi điều xấu.', 'Mối quan hệ giữa chú chim nhỏ và con hổ mạnh mẽ đôi khi được hiểu là sự châm biếm xã hội. Hãy quan sát tư thế và nét mặt: mỗi bức tranh có thể mang cách diễn giải khác nhau.'],
    ['Gấu: Ungnyeo và huyền thoại lập quốc', '곰 · Gom. Hình tượng gấu gắn với Ungnyeo, người phụ nữ hóa thân từ gấu và là mẹ của Dangun trong thần thoại Hàn Quốc.', 'Trong phiên bản quen thuộc, gấu và hổ xin Hwanung cho trở thành người. Ông cho chúng ngải cứu và tỏi, yêu cầu tránh ánh nắng một trăm ngày. Hổ bỏ cuộc, còn gấu vượt qua thử thách và trở thành Ungnyeo.', 'Ungnyeo và Hwanung sinh ra Dangun, vị sáng lập Gojoseon theo truyền thuyết. Đây là huyền thoại lập quốc, không phải tiểu sử được kiểm chứng, kể về sự biến đổi và mối liên hệ giữa trời với con người.'],
    ['Hổ: vị bảo hộ núi rừng', '호랑이 · Horangi. Trong nghệ thuật Hàn Quốc, hổ có thể là vị bảo hộ, bạn đồng hành của thần núi hoặc một nhân vật hài hước.', 'Tranh hổ mang ý nghĩa xua đuổi tai ương. Trong tranh Sansin, hổ xuất hiện bên thần núi; còn trong minhwa, đôi mắt to và biểu cảm vui nhộn khiến hổ trở nên gần gũi.', 'Hình tượng ấy tiếp tục qua linh vật hiện đại: Hodori của Olympic Seoul 1988 và hổ trắng Soohorang của Olympic mùa đông PyeongChang 2018.'],
  ],
  km: [
    ['សត្វសារិកា៖ អ្នកនាំដំណឹងល្អ', '까치 · Kkachi។ ក្នុងប្រពៃណីកូរ៉េ បក្សីនេះតំណាងឱ្យសេចក្តីរីករាយ និងដំណឹងល្អ។ វាក៏លេចឡើងក្នុងគំនូរប្រជាប្រិយ minhwa ផងដែរ។', 'គំនូរដែលគេស្គាល់បង្ហាញបក្សី ខ្លា និងដើមស្រល់ជាមួយគ្នា។ បក្សីតំណាងឱ្យសេចក្តីរីករាយ ស្រល់តំណាងឱ្យអាយុវែង ហើយខ្លាតំណាងឱ្យការការពារពីគ្រោះអាក្រក់។', 'ទំនាក់ទំនងរវាងបក្សីតូច និងខ្លាដ៏ខ្លាំងក៏អាចត្រូវបានបកស្រាយជាការចំអកសង្គម។ កាយវិការ និងទឹកមុខបន្ថែមភាពកំប្លែង ហើយគំនូរនីមួយៗអាចមានន័យខុសគ្នា។'],
    ['ខ្លាឃ្មុំ៖ រឿងនាង Ungnyeo', '곰 · Gom។ ខ្លាឃ្មុំមានទំនាក់ទំនងនឹងនាង Ungnyeo ដែលប្រែក្លាយជាមនុស្ស និងក្លាយជាម្តាយរបស់ Dangun ក្នុងទេវកថាកូរ៉េ។', 'ក្នុងរឿងដ៏ល្បី ខ្លាឃ្មុំ និងខ្លាសុំ Hwanung ឱ្យពួកវាក្លាយជាមនុស្ស។ គាត់ផ្តល់ស្លឹករុក្ខជាតិ mugwort និងខ្ទឹមស ហើយប្រាប់ឱ្យជៀសពន្លឺថ្ងៃមួយរយថ្ងៃ។ ខ្លាបោះបង់ ប៉ុន្តែខ្លាឃ្មុំបានសម្រេច ហើយក្លាយជានាង Ungnyeo។', 'Ungnyeo និង Hwanung មានកូនឈ្មោះ Dangun ដែលជាអ្នកបង្កើត Gojoseon តាមរឿងព្រេង។ នេះជាទេវកថាអំពីកំណើតរដ្ឋ មិនមែនជាជីវប្រវត្តិដែលបានបញ្ជាក់តាមប្រវត្តិសាស្ត្រទេ។'],
    ['ខ្លា៖ អ្នកការពារភ្នំ និងនិមិត្តរូបវប្បធម៌', '호랑이 · Horangi។ សិល្បៈកូរ៉េបង្ហាញខ្លាជាអ្នកការពារ ជាដៃគូរបស់ទេវតាភ្នំ និងជាតួអង្គកំប្លែងផងដែរ។', 'គំនូរខ្លាមានន័យការពារពីគ្រោះអាក្រក់។ ក្នុងគំនូរ Sansin ខ្លានៅក្បែរទេវតាភ្នំ។ ក្នុងគំនូរ minhwa ភ្នែកធំ និងទឹកមុខកំប្លែងអាចធ្វើឱ្យវាមើលទៅរួសរាយ។', 'រូបភាពនេះបន្តក្នុងសម័យថ្មី៖ Hodori ជាតុក្កតាតំណាងអូឡាំពិកសេអ៊ូលឆ្នាំ 1988 ហើយខ្លាស Soohorang តំណាងអូឡាំពិករដូវរងា PyeongChang ឆ្នាំ 2018។'],
  ],
  kk: [
    ['Сауысқан: жақсы хабардың жаршысы', '까치 · Ккачхи. Корей дәстүрінде сауысқан қуаныш пен жақсы хабарды білдіреді. Ол минхва халық кескіндемесінде жиі кездеседі.', 'Белгілі суреттерде сауысқан жолбарыс және қарағаймен бірге бейнеленеді. Құс қуанышты, қарағай ұзақ өмірді, жолбарыс жамандықтан қорғауды білдіруі мүмкін.', 'Кішкентай құс пен күшті жолбарыстың қатынасы кейде әлеуметтік әжуа ретінде түсіндіріледі. Олардың қимылы мен кейпіне назар аударыңыз: әр туындының мағынасы бірдей емес.'],
    ['Аю: Уннё және елдің басталуы туралы миф', '곰 · Ком. Аю бейнесі корей мифіндегі адамға айналып, Тангунның анасы болған Уннёмен байланысты.', 'Кең тараған нұсқада аю мен жолбарыс Хвануннан адамға айналдыруды сұрайды. Ол жусан мен сарымсақ беріп, жүз күн күн сәулесінен аулақ болуды тапсырады. Жолбарыс шыдамайды, ал аю Уннё есімді әйелге айналады.', 'Уннё мен Хванунның ұлы Тангун аңызда Кочосонның негізін қалаушы саналады. Бұл құжатпен расталған өмірбаян емес, аспан мен адам әлемінің байланысын және өзгерісті баяндайтын миф.'],
    ['Жолбарыс: тау қорғаушысы және мәдени нышан', '호랑이 · Хоранъи. Корей өнерінде жолбарыс қорғаушы, тау рухының серігі немесе күлкілі кейіпкер ретінде көрінеді.', 'Жолбарыс суреттері жамандықтан қорғау мағынасында қолданылған. Сансин бейнелерінде ол тау рухының жанында болады, ал минхвада үлкен көзі мен қызық кейпі оны жылы жүзді етіп көрсетеді.', 'Бұл бейне қазіргі тұмарларда да жалғасады: Ходори 1988 жылғы Сеул Олимпиадасының, ал ақ жолбарыс Сухоран 2018 жылғы Пхёнчхан қысқы Олимпиадасының тұмары болды.'],
  ],
};

const ids = ['magpie', 'bear', 'tiger'];
const sources = [
  ['https://www.korea.net/koreanet/fileDownload?fileUrl=FILE%2FPDF%2Fother%2F20131205_2014_Diary.pdf', 'Korea.net'],
  ['https://www.aks.ac.kr/ikorea/upload/intl/korean/UserFiles/Infokorea_2017_eng.pdf', 'Academy of Korean Studies'],
  ['https://www.nfm.go.kr/user/planexhibition/home/20/selectPlanExhibitionLView.do?page=1&planExhibitionIdx=851', 'National Folk Museum of Korea'],
];

export default function KoreaAnimals({ language }: { language: Language }) {
  return <>{articles[language].map(([title, intro, tradition, detail], index) =>
    <article className="korea-story" id={ids[index]} key={ids[index]} aria-labelledby={`${ids[index]}-title`}>
      <h2 id={`${ids[index]}-title`}>{title}</h2>
      <p className="korea-story-intro">{intro}</p>
      <Image className="korea-story-art" src={`/korea-story/${ids[index]}-comic.webp`} alt={title} width={2172} height={724} sizes="(max-width: 760px) 100vw, 1264px" style={{ marginBottom: 28 }} />
      <p className="korea-story-intro">{tradition}</p>
      <p className="korea-story-intro">{detail}</p>
      <div className="source-row"><a href={sources[index][0]} target="_blank" rel="noreferrer">{copy[language][41]} · {sources[index][1]} ↗</a></div>
    </article>
  )}</>;
}
