import Image from 'next/image';
import type { Language } from './content';

const story: Record<Language, { title: string; intro: string; parts: [string, string][] }> = {
  ru: { title: 'Южная Корея: традиции, ритм города и природа', intro: 'Республика Корея занимает южную часть Корейского полуострова. Здесь дворцы и кварталы традиционных домов соседствуют с небоскрёбами, а после прогулки по шумному городу можно оказаться на горной тропе или у моря. Знакомство со страной складывается из таких контрастов — и небольших повседневных открытий.', parts: [
    ['Прошлое рядом с будущим', 'Сеул, столица страны, объединяет деловые районы, рынки и памятники эпохи Чосон. Во дворце Кёнбоккун и кварталах ханок можно увидеть традиционную архитектуру, а в музеях — познакомиться с историей и искусством. Хангыль, корейская письменность, остаётся важной частью национальной культуры. Музыка, кино и дизайн показывают её современную сторону.'],
    ['Корея за общим столом', 'Еда — один из самых приятных способов узнать страну. Кимчи, пибимпап, супы и небольшие закуски панчхан делают корейский стол разнообразным. На рынках готовят токпокки и другие уличные блюда, а городские кафе предлагают место для встречи и отдыха. Вкус и острота отличаются от блюда к блюду: разговор о составе помогает выбрать то, что понравится именно вам.'],
    ['От горных троп до морского берега', 'За пределами столицы открывается другая Корея. Пусан сочетает городскую жизнь с морем, Кёнджу хранит наследие древнего государства Силла, а остров Чеджу известен вулканическими ландшафтами. Весной пейзажи украшают цветущие деревья, осенью — яркая листва. Своя Корея может начаться с дворца, прогулки у воды или простого разговора: ESX помогает сделать этот разговор понятнее.'] ] },
  en: { title: 'South Korea: tradition, city life and nature', intro: 'The Republic of Korea occupies the southern part of the Korean Peninsula. Palaces and traditional houses stand alongside skyscrapers, while mountains and coastlines offer a different pace beyond the city.', parts: [['Past and present', 'Seoul brings together royal palaces, markets and modern business districts. Gyeongbokgung and hanok neighborhoods reveal traditional architecture. Hangul is an important part of Korean culture, alongside the contemporary worlds of music, cinema and design.'], ['A place at the table', 'Kimchi, bibimbap, soups and small side dishes called banchan bring variety to Korean meals. Markets serve tteokbokki and other street food, while cafés offer places to meet. Ask about ingredients and spice levels to find a dish you enjoy.'], ['Mountains and sea', 'Busan combines urban life with the coast, Gyeongju preserves the heritage of ancient Silla, and Jeju is known for volcanic landscapes. Spring blossoms and autumn foliage give each season its character. A simple conversation can be the beginning of your own Korea — with ESX helping you understand each other.']] },
  ko: { title: '대한민국: 전통, 도시의 활기 그리고 자연', intro: '한반도 남부에 자리한 대한민국에서는 궁궐과 한옥, 고층 빌딩이 어우러집니다. 도시를 벗어나면 산길과 바다가 또 다른 풍경을 보여 줍니다.', parts: [['과거와 현재의 만남', '서울에서는 경복궁과 한옥 마을, 시장과 현대적인 도심을 함께 만날 수 있습니다. 한글과 전통문화는 음악, 영화, 디자인과 함께 한국의 다양한 모습을 전합니다.'], ['함께 즐기는 식탁', '김치, 비빔밥, 국과 반찬은 한국의 식탁을 다채롭게 만듭니다. 시장에서는 떡볶이 같은 길거리 음식을 맛볼 수 있습니다. 재료와 매운 정도를 물어보며 취향에 맞는 음식을 찾아보세요.'], ['산과 바다로 이어지는 여행', '부산에는 바다가, 경주에는 신라의 유산이, 제주에는 화산 지형이 있습니다. 봄꽃과 가을 단풍은 계절마다 다른 매력을 더합니다. ESX와 함께 서로를 이해하는 대화로 나만의 한국을 발견해 보세요.']] },
  zh: { title: '韩国：传统、城市与自然', intro: '韩国位于朝鲜半岛南部。宫殿、韩屋与高楼相邻，走出城市还能遇见山林与海岸。', parts: [['过去与现在', '首尔的景福宫、韩屋街区和市场展现传统文化，现代城区则呈现另一种节奏。韩文、音乐、电影和设计共同构成韩国的文化面貌。'], ['餐桌上的相遇', '泡菜、拌饭、汤和小菜让韩国餐桌丰富多样。市场里有辣炒年糕等街头美食，咖啡馆适合相聚。点餐时可以询问食材与辣度。'], ['山海之间', '釜山连接城市与大海，庆州保存新罗遗产，济州以火山地貌闻名。春花与秋叶各有魅力。让ESX帮助彼此理解，从一段对话开始发现自己的韩国。']] },
  tr: { title: 'Güney Kore: gelenek, şehir ve doğa', intro: 'Kore Yarımadası’nın güneyinde saraylar ve geleneksel evler gökdelenlerle yan yana durur. Şehirlerin ötesinde dağ yolları ve kıyılar uzanır.', parts: [['Geçmiş ve bugün', 'Seul’de Gyeongbokgung Sarayı, hanok mahalleleri ve pazarlar modern yaşamla buluşur. Hangul yazısı, müzik, sinema ve tasarım Kore kültürünün farklı yönlerini anlatır.'], ['Sofrada buluşma', 'Kimchi, bibimbap, çorbalar ve banchan adı verilen küçük yan yemekler sofraları zenginleştirir. Pazarlarda tteokbokki gibi sokak lezzetleri bulunur. İçerikleri ve acılık derecesini sorarak seçiminizi yapabilirsiniz.'], ['Dağlar ve deniz', 'Busan denizi şehirle birleştirir; Gyeongju, Silla mirasını korur; Jeju volkanik manzaralarıyla tanınır. İlkbahar çiçekleri ve sonbahar yaprakları farklı güzellikler sunar. ESX ile bir sohbet, kendi Kore’nizi keşfetmenin başlangıcı olabilir.']] },
  vi: { title: 'Hàn Quốc: truyền thống, đô thị và thiên nhiên', intro: 'Nằm ở phía nam bán đảo Triều Tiên, Hàn Quốc kết hợp cung điện, nhà truyền thống và những tòa nhà cao tầng. Ngoài đô thị là núi rừng và bờ biển.', parts: [['Quá khứ và hiện tại', 'Seoul có cung Gyeongbokgung, khu nhà hanok, chợ và những khu phố hiện đại. Chữ Hangul, âm nhạc, điện ảnh và thiết kế thể hiện nhiều khía cạnh của văn hóa Hàn Quốc.'], ['Gặp nhau bên bàn ăn', 'Kimchi, bibimbap, canh và các món ăn kèm banchan tạo nên bữa ăn đa dạng. Chợ có tteokbokki và nhiều món đường phố. Hãy hỏi về nguyên liệu và độ cay để chọn món phù hợp.'], ['Từ núi đến biển', 'Busan gắn đô thị với biển, Gyeongju lưu giữ di sản Silla, còn Jeju nổi tiếng với địa hình núi lửa. Hoa xuân và lá thu mang đến những sắc màu riêng. ESX giúp bạn hiểu nhau hơn qua từng cuộc trò chuyện.']] },
  km: { title: 'កូរ៉េខាងត្បូង៖ ប្រពៃណី ទីក្រុង និងធម្មជាតិ', intro: 'ប្រទេសកូរ៉េខាងត្បូងស្ថិតនៅភាគខាងត្បូងនៃឧបទ្វីបកូរ៉េ។ ព្រះរាជវាំង និងផ្ទះបុរាណនៅក្បែរអគារខ្ពស់ៗ ខណៈភ្នំ និងសមុទ្រផ្តល់ទេសភាពផ្សេងទៀត។', parts: [['អតីតកាល និងបច្ចុប្បន្ន', 'ទីក្រុងសេអ៊ូលមានព្រះរាជវាំង Gyeongbokgung ភូមិហាណុក ផ្សារ និងតំបន់ទំនើប។ អក្សរហាន់ហ្គុល តន្ត្រី ភាពយន្ត និងការរចនា បង្ហាញពីវប្បធម៌កូរ៉េ។'], ['ជួបគ្នានៅតុអាហារ', 'គីមឈី ប៊ីប៊ីមបាប់ ស៊ុប និងម្ហូបបន្ទាប់បន្សំ បង្កើតភាពចម្រុះ។ នៅផ្សារមានតុកប៉ុកគី និងអាហារតាមផ្លូវ។ សួរអំពីគ្រឿងផ្សំ និងកម្រិតហឹរមុនពេលជ្រើសរើស។'], ['ភ្នំ និងសមុទ្រ', 'ប៊ូសានមានឆ្នេរសមុទ្រ ក្យុងជូរក្សាបេតិកភណ្ឌស៊ីឡា ហើយជេជូល្បីដោយទេសភាពភ្នំភ្លើង។ ផ្កានិទាឃរដូវ និងស្លឹកឈើរដូវស្លឹកឈើជ្រុះមានសម្រស់ខុសៗគ្នា។ ESX ជួយឱ្យការសន្ទនាកាន់តែយល់គ្នា។']] },
  kk: { title: 'Оңтүстік Корея: дәстүр, қала және табиғат', intro: 'Корея түбегінің оңтүстігінде орналасқан елде сарайлар мен дәстүрлі үйлер зәулім ғимараттармен қатар тұр. Қаладан тыс жерде тау соқпақтары мен теңіз жағалауы күтіп тұр.', parts: [['Өткен мен бүгін', 'Сеулдегі Кёнбоккун сарайы, ханок үйлері мен базарлар заманауи аудандармен қатар өмір сүреді. Хангыль жазуы, музыка, кино және дизайн Корея мәдениетінің әр қырын көрсетеді.'], ['Дастарқан басындағы кездесу', 'Кимчи, пибимпап, сорпалар мен панчхан тіскебасарлары корей дастарқанын толықтырады. Базарларда токпокки және көше тағамдары ұсынылады. Құрамы мен ащылығын сұрап, өзіңізге ұнайтын тағамды таңдаңыз.'], ['Таудан теңізге дейін', 'Пусан қала өмірін теңізбен ұштастырады, Кёнджу Силла мұрасын сақтайды, ал Чеджу жанартаулық табиғатымен танымал. Көктем гүлдері мен күзгі жапырақтар ерекше көрік береді. ESX арқылы әңгімелесіп, өз Кореяңызды ашыңыз.']] },
};
export default function KoreaStory({ language }: { language: Language }) {
  const t = story[language];
  return <article className="korea-story" aria-labelledby="korea-story-title">
    <h2 id="korea-story-title">{t.title}</h2><p className="korea-story-intro">{t.intro}</p>
    <Image className="korea-story-art" src="/korea-story/discover-korea.webp" alt={t.parts.map(part => part[0]).join(' · ')} width={1800} height={600} sizes="(max-width: 760px) 100vw, 1264px" />
    <div className="korea-story-columns">{t.parts.map(([title, text], i) => <section className="korea-story-part" key={title}><span aria-hidden="true">0{i + 1}</span><h3>{title}</h3><p>{text}</p></section>)}</div>
  </article>;
}
