import type { Language } from './content';

const articles: Record<Language, string[]> = {
  ru: ['K-pop: музыка, которая объединяет', 'Корейская поп-музыка — часть современной культуры Южной Кореи. В ней встречаются поп, хип-хоп, R&B и электронное звучание, а песни становятся частью большого визуального мира: клипов, танцев, сценических образов и концертов.', 'Больше, чем песня', 'В K-pop музыка и выступление тесно связаны. Хореография подчёркивает ритм и настроение композиции, а костюмы и декорации помогают рассказать историю. У каждого нового релиза может быть своя концепция — от яркого и лёгкого настроения до драматичного звучания. При этом за пределами громких хитов есть баллады, сольные проекты и музыкальные эксперименты.', 'Культура участия', 'Поклонники обсуждают релизы, учат движения из клипов, создают танцевальные каверы и знакомятся на концертах. Фандом — это сообщество вокруг исполнителя, где люди делятся впечатлениями и творчеством. Для многих интерес к музыке становится первым шагом к изучению корейского языка, моды и культуры.', 'Как открыть свой K-pop', 'Начните с нескольких разных исполнителей и сравните студийные записи с живыми выступлениями. Посмотрите танцевальную репетицию: она помогает заметить детали, которые теряются в монтаже клипа. Знакомые мелодии могут стать поводом для разговора с людьми из других стран — обсудить любимую песню, обменяться впечатлениями и найти общие интересы.'],
  en: ['K-pop: music that brings people together', 'Korean pop music blends pop, hip-hop, R&B and electronic sounds. Songs are part of a visual world of music videos, choreography, stage outfits and concerts.', 'More than a song', 'Music and performance work together in K-pop. Choreography expresses the rhythm, while costumes and sets tell a story. Each release can explore a different concept. Beyond the big hits, there are ballads, solo projects and musical experiments.', 'A culture of participation', 'Fans discuss releases, learn dances, create covers and meet at concerts. Fandoms are communities where people share their enthusiasm and creativity. Music can also inspire an interest in Korean language, fashion and culture.', 'Discover your own K-pop', 'Try several artists and compare studio recordings with live performances. Dance practice videos reveal details that music-video editing can hide. A favorite song can start a conversation with someone from another country.'],
  ko: ['K-pop: 사람을 연결하는 음악', '한국의 대중음악은 팝, 힙합, R&B, 전자음악을 아우릅니다. 노래는 뮤직비디오, 안무, 무대 의상과 공연으로 이어집니다.', '노래 그 이상의 경험', '안무는 곡의 리듬과 분위기를 표현하고 의상과 무대는 이야기를 더합니다. 앨범마다 새로운 콘셉트를 선보이기도 합니다. 히트곡 외에도 발라드, 솔로 활동과 다양한 음악적 시도가 있습니다.', '함께 만드는 문화', '팬들은 신곡을 이야기하고 춤을 배우며 커버 영상을 만듭니다. 팬덤은 관심과 창작물을 나누는 공동체입니다. 음악에 대한 관심은 한국어와 패션, 문화로 이어지기도 합니다.', '나만의 K-pop 찾기', '여러 아티스트의 곡과 라이브 무대를 비교해 보세요. 안무 연습 영상에서는 뮤직비디오와 다른 세부 동작을 볼 수 있습니다. 좋아하는 노래로 다른 나라의 사람들과 대화를 시작해 보세요.'],
  zh: ['K-pop：让人相遇的音乐', '韩国流行音乐融合流行、嘻哈、R&B和电子音乐，并通过MV、编舞、舞台服装与演唱会展现独特的视觉世界。', '不止一首歌', '编舞表达歌曲的节奏与情绪，服装和布景延续故事。不同作品可以呈现不同概念。热门歌曲之外，还有抒情歌、个人作品与音乐实验。', '参与的文化', '歌迷讨论新歌、学习舞蹈、制作翻跳视频，也在演出中相遇。粉丝社群分享热情与创作，音乐兴趣还可能延伸到韩语、时尚和文化。', '发现自己的K-pop', '尝试不同歌手，对比录音室作品与现场演出。舞蹈练习视频能展现MV剪辑之外的细节。一首喜欢的歌，也能成为与外国朋友交流的起点。'],
  tr: ['K-pop: insanları buluşturan müzik', 'Kore pop müziği pop, hip-hop, R&B ve elektronik sesleri buluşturur. Şarkılar; klipler, koreografi ve konserlerle görsel bir dünyaya dönüşür.', 'Bir şarkıdan fazlası', 'Dans, ritmi ve duyguyu anlatırken kostümler ve sahne hikâyeyi tamamlar. Her yeni çalışma farklı bir konsept sunabilir. Hitlerin yanında baladlar, solo projeler ve deneysel çalışmalar da vardır.', 'Katılım kültürü', 'Hayranlar yeni şarkıları tartışır, dans öğrenir ve cover videoları hazırlar. Bu topluluklar yaratıcılığı paylaşır. Müzik merakı Koreceye, modaya ve kültüre de uzanabilir.', 'Kendi K-pop dünyanı keşfet', 'Farklı sanatçıları dinleyip stüdyo kayıtlarını canlı performanslarla karşılaştırın. Dans provaları kliplerde kaçan ayrıntıları gösterir. Sevdiğiniz bir şarkı yeni bir sohbetin başlangıcı olabilir.'],
  vi: ['K-pop: âm nhạc kết nối mọi người', 'Nhạc pop Hàn Quốc kết hợp pop, hip-hop, R&B và âm thanh điện tử trong thế giới của MV, vũ đạo, trang phục sân khấu và buổi diễn.', 'Không chỉ là bài hát', 'Vũ đạo thể hiện nhịp điệu và cảm xúc, còn trang phục và sân khấu góp phần kể chuyện. Mỗi sản phẩm có thể mang một ý tưởng riêng. Ngoài các bản hit còn có ballad, dự án solo và những thử nghiệm âm nhạc.', 'Văn hóa cùng tham gia', 'Người hâm mộ thảo luận về sản phẩm mới, học nhảy và làm video cover. Cộng đồng chia sẻ niềm yêu thích và sự sáng tạo. Âm nhạc cũng có thể khơi gợi hứng thú với tiếng Hàn, thời trang và văn hóa.', 'Khám phá K-pop của bạn', 'Thử nghe nhiều nghệ sĩ và so sánh bản thu với sân khấu trực tiếp. Video luyện vũ đạo giúp thấy rõ những chi tiết trong điệu nhảy. Một bài hát yêu thích có thể mở đầu cuộc trò chuyện với bạn bè quốc tế.'],
  km: ['K-pop៖ តន្ត្រីដែលភ្ជាប់មនុស្ស', 'តន្ត្រីប៉ុបកូរ៉េរួមបញ្ចូលប៉ុប ហ៊ីបហប R&B និងតន្ត្រីអេឡិចត្រូនិក ជាមួយវីដេអូ ក្បាច់រាំ និងការប្រគំតន្ត្រី។', 'លើសពីបទចម្រៀង', 'ក្បាច់រាំបង្ហាញចង្វាក់ និងអារម្មណ៍ ខណៈសម្លៀកបំពាក់ និងឆាកជួយប្រាប់រឿង។ ក្រៅពីបទល្បីៗ ក៏មានបទមនោសញ្ចេតនា និងគម្រោងទោលផងដែរ។', 'វប្បធម៌នៃការចូលរួម', 'អ្នកគាំទ្រពិភាក្សាបទថ្មី រៀនរាំ និងបង្កើតវីដេអូ។ សហគមន៍ចែករំលែកចំណាប់អារម្មណ៍ និងការច្នៃប្រឌិត។ តន្ត្រីអាចនាំទៅរកការសិក្សាភាសា និងវប្បធម៌កូរ៉េ។', 'ស្វែងយល់ពី K-pop របស់អ្នក', 'ស្តាប់សិល្បករផ្សេងៗ ហើយប្រៀបធៀបបទថត និងការសម្តែងផ្ទាល់។ វីដេអូហាត់រាំបង្ហាញព័ត៌មានលម្អិតនៃក្បាច់រាំ។ បទដែលអ្នកចូលចិត្តអាចចាប់ផ្តើមការសន្ទនាជាមួយមិត្តថ្មី។'],
  kk: ['K-pop: адамдарды біріктіретін музыка', 'Корей поп-музыкасында поп, хип-хоп, R&B және электронды әуендер тоғысады. Әндер бейнеклиптер, би, сахналық киімдер және концерттермен толықтырылады.', 'Әннен де кең әлем', 'Хореография ырғақ пен көңіл күйді жеткізсе, киім мен сахна оқиғаны ашады. Әр шығарылымның өз тұжырымдамасы болуы мүмкін. Танымал әндерден бөлек балладалар, жеке жобалар және музыкалық тәжірибелер бар.', 'Қатысу мәдениеті', 'Жанкүйерлер жаңа әндерді талқылайды, би үйренеді және кавер бейнелер түсіреді. Қауымдастықтар қызығушылық пен шығармашылықты бөліседі. Музыка корей тіліне, сәні мен мәдениетіне қызығушылық оятуы мүмкін.', 'Өз K-pop әлеміңізді ашыңыз', 'Әртүрлі орындаушыларды тыңдап, студиялық жазбаларды жанды орындаумен салыстырыңыз. Би жаттығуының бейнелері қимылдарды жақсырақ көруге көмектеседі. Сүйікті ән жаңа таныстыққа себеп бола алады.'],
};
export default function KpopStory({ language }: { language: Language }) {
  const t = articles[language];
  return <article className="korea-story" aria-labelledby="kpop-story-title"><h2 id="kpop-story-title">{t[0]}</h2><p className="korea-story-intro">{t[1]}</p><div className="korea-story-columns">{[2, 4, 6].map((n, i) => <section className="korea-story-part" key={n}><span aria-hidden="true">0{i + 1}</span><h3>{t[n]}</h3><p>{t[n + 1]}</p></section>)}</div></article>;
}
