import type { Language } from '@/app/design/content';

const en = {
  "signOutError": "Could not sign out. Please retry.",
  "signOut": "Sign out",
  "registrationHelp": "Register to get a permanent QR code. Scan someone else’s code to chat without registering.",
  "guestConversations": "Guest conversations",
  "guestHelp": "These conversations remain available in this browser until you leave the guest session. A new account will have a separate history.",
  "conversation": "Conversation",
  "title": "My account",
  "username": "Username",
  "qrTitle": "Translator chat",
  "qrHelp": "Scan and write in your own language; the other person will read in theirs.",
  "guestChatNote": "One-time chat for unregistered users.",
  "openChat": "Open chat",
  "waitingForChat": "Waiting for someone to scan your QR code…",
  "qrLoading": "Loading your QR code…",
  "conversations": "My conversations",
  "contact": "Contact",
  "empty": "No conversations yet. Share your QR code or scan another user’s code.",
  "loadError": "Could not load your account.",
  "retry": "Retry",
  "photoSaved": "Photo saved.",
  "photoAlt": "Profile photo",
  "changePhoto": "Change photo",
  "photoSaveError": "Could not save photo. Choose a JPG, PNG or WebP up to 10 MB and retry.",
  "photoRemoveError": "Could not remove photo.",
  "removePhoto": "Remove photo",
  "saving": "Saving…",
  "scanInstruction": "Scan to start a chat",
  "noRegistration": "No registration needed",
  "pdfError": "Could not download the PDF. Try again or use Print.",
  "linkCopied": "Link copied.",
  "copyError": "Copy the link below the QR code manually.",
  "copyLink": "Copy link",
  "logoError": "Could not load the logo. Please try again.",
  "print": "Print",
  "creatingPdf": "Creating PDF…",
  "downloadPdf": "Download PDF",
  "photoLoadError": "Could not load your photo. Please select it again."
};

export type AccountMessage = keyof typeof en;
export const accountLabels: Record<Language, typeof en> = {
  en,
  ru: {
  "signOutError": "Не удалось выйти. Повторите.",
  "signOut": "Выйти",
  "registrationHelp": "Регистрация нужна для постоянного QR-кода. По чужому QR-коду можно общаться без регистрации.",
  "guestConversations": "Гостевые переписки",
  "guestHelp": "Эти переписки доступны в текущем браузере до выхода из гостевой сессии. Новый аккаунт будет иметь отдельную историю.",
  "conversation": "Переписка",
  "title": "Личный кабинет",
  "username": "Логин",
  "qrTitle": "Чат-переводчик",
  "qrHelp": "Отсканируй и пиши на своём языке, а собеседник будет читать на своём языке.",
  "guestChatNote": "Одноразовый чат для незарегистрированных пользователей.",
  "openChat": "Открыть чат",
  "waitingForChat": "Ждём, пока собеседник отсканирует ваш QR-код…",
  "qrLoading": "Загружаем ваш QR-код…",
  "conversations": "Мои переписки",
  "contact": "Собеседник",
  "empty": "Пока нет переписок. Покажите QR-код или откройте QR-код другого пользователя.",
  "loadError": "Не удалось загрузить аккаунт.",
  "retry": "Повторить",
  "photoSaved": "Фото сохранено.",
  "photoAlt": "Фото профиля",
  "changePhoto": "Изменить фото",
  "photoSaveError": "Не удалось сохранить фото. Выберите JPG, PNG или WebP до 10 МБ и повторите.",
  "photoRemoveError": "Не удалось убрать фото.",
  "removePhoto": "Убрать фото",
  "saving": "Сохраняем…",
  "scanInstruction": "Сканируйте, чтобы начать чат",
  "noRegistration": "Регистрация не нужна",
  "pdfError": "Не удалось скачать PDF. Попробуйте ещё раз или нажмите «Распечатать».",
  "linkCopied": "Ссылка скопирована.",
  "copyError": "Скопируйте ссылку под QR-кодом вручную.",
  "copyLink": "Скопировать ссылку",
  "logoError": "Не удалось загрузить логотип. Попробуйте ещё раз.",
  "print": "Распечатать",
  "creatingPdf": "Создаём PDF…",
  "downloadPdf": "Скачать PDF",
  "photoLoadError": "Не удалось загрузить фото. Попробуйте выбрать его ещё раз."
},
  ko: {
  "signOutError": "로그아웃하지 못했습니다. 다시 시도해 주세요.",
  "signOut": "로그아웃",
  "registrationHelp": "영구 QR 코드를 받으려면 가입하세요. 다른 사람의 QR 코드를 스캔하면 가입 없이 대화할 수 있습니다.",
  "guestConversations": "게스트 대화",
  "guestHelp": "게스트 세션이 유지되는 동안 이 브라우저에서 대화에 접근할 수 있습니다. 새 계정의 대화 기록은 별도로 시작됩니다.",
  "conversation": "대화",
  "title": "내 계정",
  "username": "사용자 이름",
  "qrTitle": "번역 채팅",
  "qrHelp": "QR 코드를 스캔하고 자신의 언어로 쓰세요. 상대방은 자신의 언어로 읽습니다.",
  "guestChatNote": "미가입 사용자를 위한 일회성 채팅입니다.",
  "openChat": "채팅 열기",
  "waitingForChat": "상대방이 QR 코드를 스캔하기를 기다리는 중…",
  "qrLoading": "QR 코드 불러오는 중…",
  "conversations": "내 대화",
  "contact": "대화 상대",
  "empty": "아직 대화가 없습니다. 내 QR 코드를 보여주거나 다른 사용자의 QR 코드를 스캔하세요.",
  "loadError": "계정을 불러오지 못했습니다.",
  "retry": "다시 시도",
  "photoSaved": "사진을 저장했습니다.",
  "photoAlt": "프로필 사진",
  "changePhoto": "사진 변경",
  "photoSaveError": "사진을 저장하지 못했습니다. 10MB 이하의 JPG, PNG 또는 WebP 파일을 선택하고 다시 시도하세요.",
  "photoRemoveError": "사진을 삭제하지 못했습니다.",
  "removePhoto": "사진 삭제",
  "saving": "저장 중…",
  "scanInstruction": "스캔하여 대화를 시작하세요",
  "noRegistration": "가입이 필요하지 않습니다",
  "pdfError": "PDF를 다운로드하지 못했습니다. 다시 시도하거나 인쇄를 눌러 주세요.",
  "linkCopied": "링크를 복사했습니다.",
  "copyError": "QR 코드 아래의 링크를 직접 복사해 주세요.",
  "copyLink": "링크 복사",
  "logoError": "로고를 불러오지 못했습니다. 다시 시도해 주세요.",
  "print": "인쇄",
  "creatingPdf": "PDF 생성 중…",
  "downloadPdf": "PDF 다운로드",
  "photoLoadError": "사진을 불러오지 못했습니다. 다시 선택해 주세요."
},
  zh: {
  "signOutError": "退出失败，请重试。",
  "signOut": "退出登录",
  "registrationHelp": "注册即可获得永久二维码。扫描他人的二维码，无需注册即可聊天。",
  "guestConversations": "访客聊天",
  "guestHelp": "只要访客会话仍然有效，就可以在此浏览器中查看这些聊天。新账号将使用独立的聊天记录。",
  "conversation": "聊天",
  "title": "我的账户",
  "username": "用户名",
  "qrTitle": "翻译聊天",
  "qrHelp": "扫码后用自己的语言写消息，对方会用自己的语言阅读。",
  "guestChatNote": "未注册用户的一次性聊天。",
  "openChat": "打开聊天",
  "waitingForChat": "等待对方扫描您的二维码…",
  "qrLoading": "正在加载您的二维码…",
  "conversations": "我的聊天",
  "contact": "聊天对象",
  "empty": "暂无聊天。出示您的二维码，或扫描其他用户的二维码。",
  "loadError": "无法加载账户。",
  "retry": "重试",
  "photoSaved": "照片已保存。",
  "photoAlt": "头像",
  "changePhoto": "更换照片",
  "photoSaveError": "无法保存照片。请选择不超过10MB的JPG、PNG或WebP文件，然后重试。",
  "photoRemoveError": "无法删除照片。",
  "removePhoto": "删除照片",
  "saving": "正在保存…",
  "scanInstruction": "扫描即可开始聊天",
  "noRegistration": "无需注册",
  "pdfError": "无法下载PDF。请重试或点击“打印”。",
  "linkCopied": "链接已复制。",
  "copyError": "请手动复制二维码下方的链接。",
  "copyLink": "复制链接",
  "logoError": "无法加载标志，请重试。",
  "print": "打印",
  "creatingPdf": "正在生成PDF…",
  "downloadPdf": "下载PDF",
  "photoLoadError": "无法加载照片，请重新选择。"
},
  tr: {
  "signOutError": "Çıkış yapılamadı. Lütfen tekrar deneyin.",
  "signOut": "Çıkış yap",
  "registrationHelp": "Kalıcı bir QR kodu almak için kaydolun. Başkasının kodunu tarayarak kayıt olmadan sohbet edebilirsiniz.",
  "guestConversations": "Misafir sohbetleri",
  "guestHelp": "Misafir oturumunuz açık kaldığı sürece bu sohbetlere bu tarayıcıdan erişebilirsiniz. Yeni hesabın sohbet geçmişi ayrı olacaktır.",
  "conversation": "Sohbet",
  "title": "Hesabım",
  "username": "Kullanıcı adı",
  "qrTitle": "Çevirili sohbet",
  "qrHelp": "Kodu tarayın ve kendi dilinizde yazın; karşınızdaki kişi kendi dilinde okusun.",
  "guestChatNote": "Kayıt olmayan kullanıcılar için tek seferlik sohbet.",
  "openChat": "Sohbeti aç",
  "waitingForChat": "Karşınızdaki kişinin QR kodunuzu taraması bekleniyor…",
  "qrLoading": "QR kodunuz yükleniyor…",
  "conversations": "Sohbetlerim",
  "contact": "Sohbet ettiğiniz kişi",
  "empty": "Henüz sohbet yok. QR kodunuzu gösterin veya başka bir kullanıcının kodunu tarayın.",
  "loadError": "Hesabınız yüklenemedi.",
  "retry": "Tekrar dene",
  "photoSaved": "Fotoğraf kaydedildi.",
  "photoAlt": "Profil fotoğrafı",
  "changePhoto": "Fotoğrafı değiştir",
  "photoSaveError": "Fotoğraf kaydedilemedi. En fazla 10 MB boyutunda bir JPG, PNG veya WebP seçip tekrar deneyin.",
  "photoRemoveError": "Fotoğraf kaldırılamadı.",
  "removePhoto": "Fotoğrafı kaldır",
  "saving": "Kaydediliyor…",
  "scanInstruction": "Sohbet başlatmak için tarayın",
  "noRegistration": "Kayıt gerekmez",
  "pdfError": "PDF indirilemedi. Tekrar deneyin veya Yazdır seçeneğini kullanın.",
  "linkCopied": "Bağlantı kopyalandı.",
  "copyError": "QR kodunun altındaki bağlantıyı elle kopyalayın.",
  "copyLink": "Bağlantıyı kopyala",
  "logoError": "Logo yüklenemedi. Lütfen tekrar deneyin.",
  "print": "Yazdır",
  "creatingPdf": "PDF oluşturuluyor…",
  "downloadPdf": "PDF indir",
  "photoLoadError": "Fotoğrafınız yüklenemedi. Lütfen yeniden seçin."
},
  vi: {
  "signOutError": "Không thể đăng xuất. Vui lòng thử lại.",
  "signOut": "Đăng xuất",
  "registrationHelp": "Đăng ký để nhận mã QR cố định. Quét mã của người khác để trò chuyện mà không cần đăng ký.",
  "guestConversations": "Cuộc trò chuyện của khách",
  "guestHelp": "Bạn có thể truy cập các cuộc trò chuyện này trong trình duyệt hiện tại khi phiên khách còn được lưu. Tài khoản mới sẽ có lịch sử riêng.",
  "conversation": "Cuộc trò chuyện",
  "title": "Tài khoản của tôi",
  "username": "Tên người dùng",
  "qrTitle": "Trò chuyện phiên dịch",
  "qrHelp": "Quét mã và viết bằng ngôn ngữ của bạn; người đối thoại sẽ đọc bằng ngôn ngữ của họ.",
  "guestChatNote": "Cuộc trò chuyện dùng một lần dành cho người chưa đăng ký.",
  "openChat": "Mở trò chuyện",
  "waitingForChat": "Đang chờ người đối thoại quét mã QR của bạn…",
  "qrLoading": "Đang tải mã QR của bạn…",
  "conversations": "Cuộc trò chuyện của tôi",
  "contact": "Người trò chuyện",
  "empty": "Chưa có cuộc trò chuyện. Hãy chia sẻ mã QR của bạn hoặc quét mã của người khác.",
  "loadError": "Không thể tải tài khoản của bạn.",
  "retry": "Thử lại",
  "photoSaved": "Đã lưu ảnh.",
  "photoAlt": "Ảnh hồ sơ",
  "changePhoto": "Đổi ảnh",
  "photoSaveError": "Không thể lưu ảnh. Hãy chọn tệp JPG, PNG hoặc WebP tối đa 10 MB rồi thử lại.",
  "photoRemoveError": "Không thể xóa ảnh.",
  "removePhoto": "Xóa ảnh",
  "saving": "Đang lưu…",
  "scanInstruction": "Quét để bắt đầu trò chuyện",
  "noRegistration": "Không cần đăng ký",
  "pdfError": "Không thể tải PDF. Hãy thử lại hoặc chọn In.",
  "linkCopied": "Đã sao chép liên kết.",
  "copyError": "Hãy sao chép thủ công liên kết bên dưới mã QR.",
  "copyLink": "Sao chép liên kết",
  "logoError": "Không thể tải logo. Vui lòng thử lại.",
  "print": "In",
  "creatingPdf": "Đang tạo PDF…",
  "downloadPdf": "Tải PDF",
  "photoLoadError": "Không thể tải ảnh của bạn. Vui lòng chọn lại."
},
  km: {
  "signOutError": "មិនអាចចេញពីគណនីបានទេ។ សូមព្យាយាមម្ដងទៀត។",
  "signOut": "ចេញពីគណនី",
  "registrationHelp": "ចុះឈ្មោះដើម្បីទទួលបានកូដ QR អចិន្ត្រៃយ៍។ ស្កេនកូដរបស់អ្នកដទៃដើម្បីជជែកដោយមិនចាំបាច់ចុះឈ្មោះ។",
  "guestConversations": "ការសន្ទនារបស់ភ្ញៀវ",
  "guestHelp": "អ្នកអាចចូលមើលការសន្ទនាទាំងនេះក្នុងកម្មវិធីរុករកនេះ ដរាបណាវគ្គប្រើប្រាស់ជាភ្ញៀវនៅតែត្រូវបានរក្សាទុក។ គណនីថ្មីនឹងមានប្រវត្តិសន្ទនាដាច់ដោយឡែក។",
  "conversation": "ការសន្ទនា",
  "title": "គណនីរបស់ខ្ញុំ",
  "username": "ឈ្មោះអ្នកប្រើប្រាស់",
  "qrTitle": "ការជជែកបកប្រែ",
  "qrHelp": "ស្កេនហើយសរសេរជាភាសារបស់អ្នក។ ដៃគូសន្ទនានឹងអានជាភាសារបស់ពួកគេ។",
  "guestChatNote": "ការជជែកប្រើតែម្តងសម្រាប់អ្នកប្រើដែលមិនបានចុះឈ្មោះ។",
  "openChat": "បើកការជជែក",
  "waitingForChat": "កំពុងរង់ចាំដៃគូសន្ទនាស្កេនកូដ QR របស់អ្នក…",
  "qrLoading": "កំពុងផ្ទុកកូដ QR របស់អ្នក…",
  "conversations": "ការសន្ទនារបស់ខ្ញុំ",
  "contact": "ដៃគូសន្ទនា",
  "empty": "មិនទាន់មានការសន្ទនាទេ។ បង្ហាញកូដ QR របស់អ្នក ឬស្កេនកូដរបស់អ្នកប្រើប្រាស់ផ្សេង។",
  "loadError": "មិនអាចផ្ទុកគណនីរបស់អ្នកបានទេ។",
  "retry": "ព្យាយាមម្ដងទៀត",
  "photoSaved": "បានរក្សាទុករូបថត។",
  "photoAlt": "រូបថតប្រវត្តិរូប",
  "changePhoto": "ប្ដូររូបថត",
  "photoSaveError": "មិនអាចរក្សាទុករូបថតបានទេ។ សូមជ្រើសរើសឯកសារ JPG, PNG ឬ WebP ដែលមានទំហំមិនលើស 10 MB ហើយព្យាយាមម្ដងទៀត។",
  "photoRemoveError": "មិនអាចលុបរូបថតបានទេ។",
  "removePhoto": "លុបរូបថត",
  "saving": "កំពុងរក្សាទុក…",
  "scanInstruction": "ស្កេនដើម្បីចាប់ផ្ដើមជជែក",
  "noRegistration": "មិនចាំបាច់ចុះឈ្មោះទេ",
  "pdfError": "មិនអាចទាញយក PDF បានទេ។ សូមព្យាយាមម្ដងទៀត ឬចុច បោះពុម្ព។",
  "linkCopied": "បានចម្លងតំណ។",
  "copyError": "សូមចម្លងតំណនៅខាងក្រោមកូដ QR ដោយខ្លួនឯង។",
  "copyLink": "ចម្លងតំណ",
  "logoError": "មិនអាចផ្ទុកនិមិត្តសញ្ញាបានទេ។ សូមព្យាយាមម្ដងទៀត។",
  "print": "បោះពុម្ព",
  "creatingPdf": "កំពុងបង្កើត PDF…",
  "downloadPdf": "ទាញយក PDF",
  "photoLoadError": "មិនអាចផ្ទុករូបថតរបស់អ្នកបានទេ។ សូមជ្រើសរើសម្ដងទៀត។"
},
  kk: {
  "signOutError": "Аккаунттан шығу мүмкін болмады. Қайталап көріңіз.",
  "signOut": "Шығу",
  "registrationHelp": "Тұрақты QR-код алу үшін тіркеліңіз. Басқа адамның кодын сканерлеп, тіркелмей сөйлесе аласыз.",
  "guestConversations": "Қонақ ретінде жазысулар",
  "guestHelp": "Қонақ сеансы сақталғанша, бұл жазысулар осы браузерде қолжетімді болады. Жаңа аккаунттың жазысу тарихы бөлек болады.",
  "conversation": "Жазысу",
  "title": "Жеке кабинет",
  "username": "Пайдаланушы аты",
  "qrTitle": "Аудармашы чат",
  "qrHelp": "Сканерлеп, өз тіліңізде жазыңыз, ал сұхбаттасыңыз өз тілінде оқиды.",
  "guestChatNote": "Тіркелмеген пайдаланушыларға арналған бір реттік чат.",
  "openChat": "Чатты ашу",
  "waitingForChat": "Сұхбаттасыңыз QR-кодыңызды сканерлегенше күтеміз…",
  "qrLoading": "QR-кодыңыз жүктелуде…",
  "conversations": "Менің жазысуларым",
  "contact": "Сұхбаттас",
  "empty": "Әзірге жазысулар жоқ. QR-кодыңызды көрсетіңіз немесе басқа пайдаланушының кодын сканерлеңіз.",
  "loadError": "Аккаунтты жүктеу мүмкін болмады.",
  "retry": "Қайталау",
  "photoSaved": "Фото сақталды.",
  "photoAlt": "Профиль фотосы",
  "changePhoto": "Фотоны өзгерту",
  "photoSaveError": "Фотоны сақтау мүмкін болмады. Көлемі 10 МБ-тан аспайтын JPG, PNG немесе WebP файлын таңдап, қайталап көріңіз.",
  "photoRemoveError": "Фотоны жою мүмкін болмады.",
  "removePhoto": "Фотоны жою",
  "saving": "Сақталуда…",
  "scanInstruction": "Сөйлесуді бастау үшін сканерлеңіз",
  "noRegistration": "Тіркелу қажет емес",
  "pdfError": "PDF жүктеп алу мүмкін болмады. Қайталап көріңіз немесе «Басып шығару» түймесін басыңыз.",
  "linkCopied": "Сілтеме көшірілді.",
  "copyError": "QR-кодтың астындағы сілтемені қолмен көшіріңіз.",
  "copyLink": "Сілтемені көшіру",
  "logoError": "Логотипті жүктеу мүмкін болмады. Қайталап көріңіз.",
  "print": "Басып шығару",
  "creatingPdf": "PDF жасалуда…",
  "downloadPdf": "PDF жүктеп алу",
  "photoLoadError": "Фотоңызды жүктеу мүмкін болмады. Оны қайта таңдаңыз."
}
};
