import type { Language } from '@/app/design/content';

const en = {
  "accountExists": "An account with this email already exists. Open the Sign in tab.",
  "invalidCredentials": "Incorrect email or password.",
  "emailUnconfirmed": "Confirm your email: enter the code from your email or request a new one.",
  "emailUnavailable": "Email delivery is currently unavailable. Please try again later.",
  "weakPassword": "Choose a stronger password with at least 8 characters.",
  "rateLimit": "Too many attempts. Please try again later.",
  "requestFailed": "The request failed. Please try again later.",
  "invalidUsername": "Username: 3–24 English letters, numbers or _. Start with a letter or number.",
  "passwordMismatch": "Passwords do not match.",
  "emailResent": "A new code has been sent to your email.",
  "tabs": "Sign in or register",
  "register": "Register",
  "signIn": "Sign in",
  "confirmEmail": "Confirm your email",
  "checkInbox": "Check your inbox at",
  "confirmationHelp": "Enter the code from the email. If it is missing, check your spam folder.",
  "resend": "Resend code",
  "changeEmail": "Change email",
  "createTitle": "Create your ESX account",
  "welcome": "Welcome back",
  "registerHelp": "Choose a username, enter your email and create a password. Then confirm your email with the six-digit code we send you.",
  "signInHelp": "Enter your email and password to open your account.",
  "username": "Username",
  "usernameHelp": "3–24 English letters, numbers or _. Use your email to sign in.",
  "email": "Email",
  "password": "Password",
  "passwordHelp": "At least 8 characters.",
  "confirmPassword": "Confirm password",
  "showPassword": "Show password",
  "wait": "Please wait…",
  "createAccount": "Create account",
  "authError": "Could not confirm your email. Sign in with your email and password, then request a new code.",
  "resendCountdown": "Resend in {seconds}s",
  "home": "← ESX · Home",
  "loading": "Loading…",
  "emailCode": "Email code",
  "codeHelp": "6 digits. Confirm the code to open your account.",
  "verifyCode": "Confirm and sign in",
  "invalidCode": "The code is incorrect or has expired. Check it or request a new one.",
  "codeRequired": "Enter the six-digit code from your email."
};

export type RegistrationLabels = typeof en;
export type RegistrationMessage = keyof RegistrationLabels;

export const registrationLabels: Record<Language, RegistrationLabels> = {
  en,
  ru: {
  "accountExists": "Аккаунт с этой почтой уже существует. Перейдите во вкладку «Вход».",
  "invalidCredentials": "Неверная почта или пароль.",
  "emailUnconfirmed": "Подтвердите почту: введите код из письма или запросите новый.",
  "emailUnavailable": "Отправка писем сейчас недоступна. Попробуйте позже.",
  "weakPassword": "Выберите более надёжный пароль, не короче 8 символов.",
  "rateLimit": "Слишком много попыток. Попробуйте немного позже.",
  "requestFailed": "Не удалось выполнить запрос. Попробуйте позже.",
  "invalidUsername": "Логин: от 3 до 24 латинских букв, цифр или _. Начните с буквы или цифры.",
  "passwordMismatch": "Пароли не совпадают.",
  "emailResent": "Новый код отправлен на почту.",
  "tabs": "Вход или регистрация",
  "register": "Регистрация",
  "signIn": "Войти",
  "confirmEmail": "Подтвердите почту",
  "checkInbox": "Проверьте почту",
  "confirmationHelp": "Введите код из письма. Если письма нет, проверьте папку «Спам».",
  "resend": "Отправить код ещё раз",
  "changeEmail": "Изменить почту",
  "createTitle": "Создайте свой ESX",
  "welcome": "С возвращением",
  "registerHelp": "Придумайте логин, введите почту и пароль. Затем подтвердите почту шестизначным кодом из письма.",
  "signInHelp": "Введите почту и пароль, чтобы открыть свой кабинет.",
  "username": "Логин",
  "usernameHelp": "3–24 латинские буквы, цифры или _. Для входа используется почта.",
  "email": "Электронная почта",
  "password": "Пароль",
  "passwordHelp": "От 8 символов.",
  "confirmPassword": "Повторите пароль",
  "showPassword": "Показать пароль",
  "wait": "Подождите…",
  "createAccount": "Зарегистрироваться",
  "authError": "Не удалось подтвердить почту. Войдите с почтой и паролем, затем запросите новый код.",
  "resendCountdown": "Повторить через {seconds} с",
  "home": "← ESX · Главная",
  "loading": "Загрузка…",
  "emailCode": "Код из письма",
  "codeHelp": "6 цифр. После подтверждения откроется личный кабинет.",
  "verifyCode": "Подтвердить и войти",
  "invalidCode": "Код неверный или срок его действия истёк. Проверьте код или запросите новый.",
  "codeRequired": "Введите шестизначный код из письма."
},
  ko: {
  "accountExists": "이 이메일로 등록된 계정이 이미 있습니다. 로그인 탭을 선택하세요.",
  "invalidCredentials": "이메일 또는 비밀번호가 올바르지 않습니다.",
  "emailUnconfirmed": "이메일로 받은 코드를 입력하거나 새 코드를 요청하여 이메일을 인증하세요.",
  "emailUnavailable": "현재 이메일을 보낼 수 없습니다. 나중에 다시 시도하세요.",
  "weakPassword": "8자 이상의 더 안전한 비밀번호를 사용하세요.",
  "rateLimit": "시도 횟수가 너무 많습니다. 잠시 후 다시 시도하세요.",
  "requestFailed": "요청을 처리하지 못했습니다. 나중에 다시 시도하세요.",
  "invalidUsername": "사용자 이름은 영문, 숫자 또는 _로 3~24자이며 영문이나 숫자로 시작해야 합니다.",
  "passwordMismatch": "비밀번호가 일치하지 않습니다.",
  "emailResent": "새 코드를 이메일로 보냈습니다.",
  "tabs": "로그인 또는 회원가입",
  "register": "회원가입",
  "signIn": "로그인",
  "confirmEmail": "이메일을 인증하세요",
  "checkInbox": "받은편지함을 확인하세요:",
  "confirmationHelp": "이메일로 받은 코드를 입력하세요. 이메일이 없으면 스팸함을 확인하세요.",
  "resend": "코드 다시 보내기",
  "changeEmail": "이메일 변경",
  "createTitle": "ESX 계정 만들기",
  "welcome": "다시 오신 것을 환영합니다",
  "registerHelp": "사용자 이름, 이메일, 비밀번호를 입력하세요. 이메일로 받은 6자리 코드로 이메일을 인증하세요.",
  "signInHelp": "이메일과 비밀번호를 입력하여 로그인하세요.",
  "username": "사용자 이름",
  "usernameHelp": "영문, 숫자 또는 _로 3~24자. 로그인에는 이메일을 사용합니다.",
  "email": "이메일",
  "password": "비밀번호",
  "passwordHelp": "8자 이상.",
  "confirmPassword": "비밀번호 확인",
  "showPassword": "비밀번호 표시",
  "wait": "잠시 기다려 주세요…",
  "createAccount": "계정 만들기",
  "authError": "이메일을 인증하지 못했습니다. 이메일과 비밀번호로 로그인을 시도한 후 새 코드를 요청하세요.",
  "resendCountdown": "{seconds}초 후 다시 보내기",
  "home": "← ESX · 홈",
  "loading": "불러오는 중…",
  "emailCode": "이메일 인증 코드",
  "codeHelp": "숫자 6자리. 인증하면 내 계정이 열립니다.",
  "verifyCode": "인증하고 로그인",
  "invalidCode": "코드가 올바르지 않거나 만료되었습니다. 코드를 확인하거나 새 코드를 요청하세요.",
  "codeRequired": "이메일로 받은 6자리 코드를 입력하세요."
},
  zh: {
  "accountExists": "此邮箱已注册账户。请切换到“登录”。",
  "invalidCredentials": "邮箱或密码不正确。",
  "emailUnconfirmed": "请输入邮件中的验证码或请求新验证码以验证邮箱。",
  "emailUnavailable": "目前无法发送邮件。请稍后重试。",
  "weakPassword": "请设置至少8个字符的更安全密码。",
  "rateLimit": "尝试次数过多。请稍后重试。",
  "requestFailed": "请求失败。请稍后重试。",
  "invalidUsername": "用户名须为3–24个英文字母、数字或下划线，且以字母或数字开头。",
  "passwordMismatch": "两次输入的密码不一致。",
  "emailResent": "新验证码已发送到您的邮箱。",
  "tabs": "登录或注册",
  "register": "注册",
  "signIn": "登录",
  "confirmEmail": "验证您的邮箱",
  "checkInbox": "请查看此邮箱的收件箱：",
  "confirmationHelp": "输入邮件中的验证码。如果未收到邮件，请检查垃圾邮件文件夹。",
  "resend": "重新发送验证码",
  "changeEmail": "更改邮箱",
  "createTitle": "创建您的 ESX 账户",
  "welcome": "欢迎回来",
  "registerHelp": "设置用户名，输入邮箱并创建密码，然后输入邮件中的6位验证码以验证邮箱。",
  "signInHelp": "输入邮箱和密码以登录账户。",
  "username": "用户名",
  "usernameHelp": "3–24个英文字母、数字或下划线。请使用邮箱登录。",
  "email": "电子邮箱",
  "password": "密码",
  "passwordHelp": "至少8个字符。",
  "confirmPassword": "确认密码",
  "showPassword": "显示密码",
  "wait": "请稍候…",
  "createAccount": "创建账户",
  "authError": "无法验证邮箱。请使用邮箱和密码登录，然后请求新的验证码。",
  "resendCountdown": "{seconds}秒后重新发送",
  "home": "← ESX · 首页",
  "loading": "加载中…",
  "emailCode": "邮箱验证码",
  "codeHelp": "6位数字。验证后即可进入个人账户。",
  "verifyCode": "验证并登录",
  "invalidCode": "验证码错误或已过期。请检查验证码或请求新的验证码。",
  "codeRequired": "请输入邮件中的6位验证码。"
},
  tr: {
  "accountExists": "Bu e-posta adresiyle bir hesap zaten var. Giriş yap sekmesini açın.",
  "invalidCredentials": "E-posta veya şifre yanlış.",
  "emailUnconfirmed": "E-postanızı doğrulayın: e-postadaki kodu girin veya yeni bir kod isteyin.",
  "emailUnavailable": "Şu anda e-posta gönderilemiyor. Lütfen daha sonra tekrar deneyin.",
  "weakPassword": "En az 8 karakterden oluşan daha güçlü bir şifre seçin.",
  "rateLimit": "Çok fazla deneme yaptınız. Lütfen biraz sonra tekrar deneyin.",
  "requestFailed": "İstek başarısız oldu. Lütfen daha sonra tekrar deneyin.",
  "invalidUsername": "Kullanıcı adı: 3–24 Latin harfi, rakam veya _. Harf veya rakamla başlayın.",
  "passwordMismatch": "Şifreler eşleşmiyor.",
  "emailResent": "E-posta adresinize yeni bir kod gönderildi.",
  "tabs": "Giriş yap veya kayıt ol",
  "register": "Kayıt ol",
  "signIn": "Giriş yap",
  "confirmEmail": "E-posta adresinizi doğrulayın",
  "checkInbox": "Gelen kutunuzu kontrol edin:",
  "confirmationHelp": "E-postadaki kodu girin. E-posta yoksa spam klasörünü kontrol edin.",
  "resend": "Kodu tekrar gönder",
  "changeEmail": "E-postayı değiştir",
  "createTitle": "ESX hesabınızı oluşturun",
  "welcome": "Tekrar hoş geldiniz",
  "registerHelp": "Bir kullanıcı adı seçin, e-postanızı girin ve şifre oluşturun. Ardından e-postanıza gelen altı haneli kodla adresinizi doğrulayın.",
  "signInHelp": "Hesabınızı açmak için e-posta adresinizi ve şifrenizi girin.",
  "username": "Kullanıcı adı",
  "usernameHelp": "3–24 Latin harfi, rakam veya _. Giriş yapmak için e-posta adresinizi kullanın.",
  "email": "E-posta",
  "password": "Şifre",
  "passwordHelp": "En az 8 karakter.",
  "confirmPassword": "Şifreyi tekrar girin",
  "showPassword": "Şifreyi göster",
  "wait": "Lütfen bekleyin…",
  "createAccount": "Hesap oluştur",
  "authError": "E-postanız doğrulanamadı. E-posta ve şifrenizle giriş yapmayı deneyin, ardından yeni bir kod isteyin.",
  "resendCountdown": "{seconds} saniye sonra tekrar gönder",
  "home": "← ESX · Ana sayfa",
  "loading": "Yükleniyor…",
  "emailCode": "E-posta kodu",
  "codeHelp": "6 rakam. Doğrulamadan sonra hesabınız açılır.",
  "verifyCode": "Doğrula ve giriş yap",
  "invalidCode": "Kod yanlış veya süresi dolmuş. Kodu kontrol edin ya da yeni bir kod isteyin.",
  "codeRequired": "E-postanıza gelen altı haneli kodu girin."
},
  vi: {
  "accountExists": "Email này đã có tài khoản. Hãy mở thẻ Đăng nhập.",
  "invalidCredentials": "Email hoặc mật khẩu không đúng.",
  "emailUnconfirmed": "Xác nhận email: nhập mã trong email hoặc yêu cầu mã mới.",
  "emailUnavailable": "Hiện không thể gửi email. Vui lòng thử lại sau.",
  "weakPassword": "Hãy chọn mật khẩu mạnh hơn với ít nhất 8 ký tự.",
  "rateLimit": "Bạn đã thử quá nhiều lần. Vui lòng thử lại sau.",
  "requestFailed": "Yêu cầu không thành công. Vui lòng thử lại sau.",
  "invalidUsername": "Tên người dùng: 3–24 chữ cái Latin, chữ số hoặc _. Bắt đầu bằng chữ cái hoặc chữ số.",
  "passwordMismatch": "Mật khẩu không khớp.",
  "emailResent": "Mã mới đã được gửi đến email của bạn.",
  "tabs": "Đăng nhập hoặc đăng ký",
  "register": "Đăng ký",
  "signIn": "Đăng nhập",
  "confirmEmail": "Xác nhận email của bạn",
  "checkInbox": "Kiểm tra hộp thư tại",
  "confirmationHelp": "Nhập mã trong email. Nếu không thấy email, hãy kiểm tra thư mục thư rác.",
  "resend": "Gửi lại mã",
  "changeEmail": "Đổi email",
  "createTitle": "Tạo tài khoản ESX của bạn",
  "welcome": "Chào mừng bạn trở lại",
  "registerHelp": "Chọn tên người dùng, nhập email và tạo mật khẩu. Sau đó xác nhận email bằng mã gồm 6 chữ số được gửi đến bạn.",
  "signInHelp": "Nhập email và mật khẩu để mở tài khoản.",
  "username": "Tên người dùng",
  "usernameHelp": "3–24 chữ cái Latin, chữ số hoặc _. Dùng email để đăng nhập.",
  "email": "Email",
  "password": "Mật khẩu",
  "passwordHelp": "Ít nhất 8 ký tự.",
  "confirmPassword": "Nhập lại mật khẩu",
  "showPassword": "Hiện mật khẩu",
  "wait": "Vui lòng chờ…",
  "createAccount": "Tạo tài khoản",
  "authError": "Không thể xác nhận email. Hãy thử đăng nhập bằng email và mật khẩu, sau đó yêu cầu mã mới.",
  "resendCountdown": "Gửi lại sau {seconds} giây",
  "home": "← ESX · Trang chủ",
  "loading": "Đang tải…",
  "emailCode": "Mã trong email",
  "codeHelp": "6 chữ số. Sau khi xác nhận, tài khoản của bạn sẽ mở.",
  "verifyCode": "Xác nhận và đăng nhập",
  "invalidCode": "Mã không đúng hoặc đã hết hạn. Hãy kiểm tra mã hoặc yêu cầu mã mới.",
  "codeRequired": "Nhập mã gồm 6 chữ số trong email."
},
  km: {
  "accountExists": "មានគណនីដែលប្រើអ៊ីមែលនេះរួចហើយ។ សូមបើកផ្ទាំងចូលគណនី។",
  "invalidCredentials": "អ៊ីមែល ឬពាក្យសម្ងាត់មិនត្រឹមត្រូវ។",
  "emailUnconfirmed": "បញ្ជាក់អ៊ីមែល៖ បញ្ចូលកូដក្នុងអ៊ីមែល ឬស្នើសុំកូដថ្មី។",
  "emailUnavailable": "ពេលនេះមិនអាចផ្ញើអ៊ីមែលបានទេ។ សូមព្យាយាមម្ដងទៀតនៅពេលក្រោយ។",
  "weakPassword": "សូមជ្រើសរើសពាក្យសម្ងាត់ដែលមានសុវត្ថិភាពជាងនេះ និងមានយ៉ាងតិច 8 តួអក្សរ។",
  "rateLimit": "បានព្យាយាមច្រើនដងពេក។ សូមព្យាយាមម្ដងទៀតនៅពេលក្រោយ។",
  "requestFailed": "សំណើមិនបានសម្រេចទេ។ សូមព្យាយាមម្ដងទៀតនៅពេលក្រោយ។",
  "invalidUsername": "ឈ្មោះអ្នកប្រើ៖ អក្សរឡាតាំង លេខ ឬ _ ចំនួន 3–24 តួ។ ត្រូវចាប់ផ្ដើមដោយអក្សរ ឬលេខ។",
  "passwordMismatch": "ពាក្យសម្ងាត់មិនត្រូវគ្នាទេ។",
  "emailResent": "បានផ្ញើកូដថ្មីទៅអ៊ីមែលរបស់អ្នកហើយ។",
  "tabs": "ចូលគណនី ឬចុះឈ្មោះ",
  "register": "ចុះឈ្មោះ",
  "signIn": "ចូលគណនី",
  "confirmEmail": "បញ្ជាក់អ៊ីមែលរបស់អ្នក",
  "checkInbox": "ពិនិត្យប្រអប់សំបុត្ររបស់អ្នកនៅ",
  "confirmationHelp": "បញ្ចូលកូដក្នុងអ៊ីមែល។ ប្រសិនបើរកមិនឃើញអ៊ីមែល សូមពិនិត្យថតសារឥតបានការ។",
  "resend": "ផ្ញើកូដម្ដងទៀត",
  "changeEmail": "ប្ដូរអ៊ីមែល",
  "createTitle": "បង្កើតគណនី ESX របស់អ្នក",
  "welcome": "សូមស្វាគមន៍មកវិញ",
  "registerHelp": "ជ្រើសរើសឈ្មោះអ្នកប្រើ បញ្ចូលអ៊ីមែល និងបង្កើតពាក្យសម្ងាត់។ បន្ទាប់មក បញ្ជាក់អ៊ីមែលដោយប្រើកូដ 6 ខ្ទង់ដែលបានផ្ញើទៅអ្នក។",
  "signInHelp": "បញ្ចូលអ៊ីមែល និងពាក្យសម្ងាត់ ដើម្បីចូលគណនីរបស់អ្នក។",
  "username": "ឈ្មោះអ្នកប្រើ",
  "usernameHelp": "អក្សរឡាតាំង លេខ ឬ _ ចំនួន 3–24 តួ។ ប្រើអ៊ីមែលដើម្បីចូលគណនី។",
  "email": "អ៊ីមែល",
  "password": "ពាក្យសម្ងាត់",
  "passwordHelp": "យ៉ាងតិច 8 តួអក្សរ។",
  "confirmPassword": "បញ្ចូលពាក្យសម្ងាត់ម្ដងទៀត",
  "showPassword": "បង្ហាញពាក្យសម្ងាត់",
  "wait": "សូមរង់ចាំ…",
  "createAccount": "បង្កើតគណនី",
  "authError": "មិនអាចបញ្ជាក់អ៊ីមែលបានទេ។ សូមព្យាយាមចូលដោយប្រើអ៊ីមែល និងពាក្យសម្ងាត់ រួចស្នើសុំកូដថ្មី។",
  "resendCountdown": "ផ្ញើម្ដងទៀតក្នុង {seconds} វិនាទី",
  "home": "← ESX · ទំព័រដើម",
  "loading": "កំពុងផ្ទុក…",
  "emailCode": "កូដក្នុងអ៊ីមែល",
  "codeHelp": "លេខ 6 ខ្ទង់។ បន្ទាប់ពីបញ្ជាក់ គណនីរបស់អ្នកនឹងបើក។",
  "verifyCode": "បញ្ជាក់ និងចូលគណនី",
  "invalidCode": "កូដមិនត្រឹមត្រូវ ឬផុតកំណត់។ សូមពិនិត្យកូដ ឬស្នើសុំកូដថ្មី។",
  "codeRequired": "បញ្ចូលកូដ 6 ខ្ទង់ក្នុងអ៊ីមែល។"
},
  kk: {
  "accountExists": "Бұл пошта мекенжайымен аккаунт тіркелген. «Кіру» қойындысын ашыңыз.",
  "invalidCredentials": "Пошта немесе құпиясөз қате.",
  "emailUnconfirmed": "Поштаңызды растаңыз: хаттағы кодты енгізіңіз немесе жаңа код сұратыңыз.",
  "emailUnavailable": "Қазір хат жіберу мүмкін емес. Кейінірек қайталап көріңіз.",
  "weakPassword": "Кемінде 8 таңбадан тұратын сенімдірек құпиясөз таңдаңыз.",
  "rateLimit": "Әрекет саны тым көп. Сәл кейінірек қайталап көріңіз.",
  "requestFailed": "Сұрау орындалмады. Кейінірек қайталап көріңіз.",
  "invalidUsername": "Пайдаланушы аты: 3–24 латын әрпі, сан немесе _. Әріптен не саннан бастаңыз.",
  "passwordMismatch": "Құпиясөздер сәйкес келмейді.",
  "emailResent": "Поштаңызға жаңа код жіберілді.",
  "tabs": "Кіру немесе тіркелу",
  "register": "Тіркелу",
  "signIn": "Кіру",
  "confirmEmail": "Поштаңызды растаңыз",
  "checkInbox": "Пошта жәшігіңізді тексеріңіз:",
  "confirmationHelp": "Хаттағы кодты енгізіңіз. Хат келмесе, «Спам» қалтасын тексеріңіз.",
  "resend": "Кодты қайта жіберу",
  "changeEmail": "Поштаны өзгерту",
  "createTitle": "ESX аккаунтын жасаңыз",
  "welcome": "Қайта қош келдіңіз",
  "registerHelp": "Пайдаланушы атын таңдап, поштаңызды енгізіңіз және құпиясөз жасаңыз. Содан кейін хаттағы алты таңбалы кодпен поштаңызды растаңыз.",
  "signInHelp": "Жеке кабинетке кіру үшін пошта мен құпиясөзді енгізіңіз.",
  "username": "Пайдаланушы аты",
  "usernameHelp": "3–24 латын әрпі, сан немесе _. Кіру үшін поштаңызды пайдаланыңыз.",
  "email": "Электрондық пошта",
  "password": "Құпиясөз",
  "passwordHelp": "Кемінде 8 таңба.",
  "confirmPassword": "Құпиясөзді қайталаңыз",
  "showPassword": "Құпиясөзді көрсету",
  "wait": "Күте тұрыңыз…",
  "createAccount": "Аккаунт жасау",
  "authError": "Поштаны растау мүмкін болмады. Пошта және құпиясөзбен кіріп көріңіз, содан кейін жаңа код сұратыңыз.",
  "resendCountdown": "{seconds} секундтан кейін қайта жіберу",
  "home": "← ESX · Басты бет",
  "loading": "Жүктелуде…",
  "emailCode": "Хаттағы код",
  "codeHelp": "6 цифр. Растағаннан кейін жеке кабинет ашылады.",
  "verifyCode": "Растау және кіру",
  "invalidCode": "Код қате немесе оның мерзімі өткен. Кодты тексеріңіз немесе жаңасын сұратыңыз.",
  "codeRequired": "Хаттағы алты таңбалы кодты енгізіңіз."
},
};
